package com.pcitc.base.system;

public class SysLogin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login.login_id
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    private String loginId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login.login_time
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    private String loginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login.login_username
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    private String loginUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login.login_userdisp
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    private String loginUserdisp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login.login_userpost
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    private String loginUserpost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login.login_userunit
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    private String loginUserunit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login.login_userunitid
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    private String loginUserunitid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login.login_unitpath
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    private String loginUnitpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login.login_clientip
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    private String loginClientip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login.login_extend
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    private String loginExtend;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login.login_id
     *
     * @return the value of sys_login.login_id
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login.login_id
     *
     * @param loginId the value for sys_login.login_id
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login.login_time
     *
     * @return the value of sys_login.login_time
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public String getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login.login_time
     *
     * @param loginTime the value for sys_login.login_time
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public void setLoginTime(String loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login.login_username
     *
     * @return the value of sys_login.login_username
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public String getLoginUsername() {
        return loginUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login.login_username
     *
     * @param loginUsername the value for sys_login.login_username
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public void setLoginUsername(String loginUsername) {
        this.loginUsername = loginUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login.login_userdisp
     *
     * @return the value of sys_login.login_userdisp
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public String getLoginUserdisp() {
        return loginUserdisp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login.login_userdisp
     *
     * @param loginUserdisp the value for sys_login.login_userdisp
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public void setLoginUserdisp(String loginUserdisp) {
        this.loginUserdisp = loginUserdisp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login.login_userpost
     *
     * @return the value of sys_login.login_userpost
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public String getLoginUserpost() {
        return loginUserpost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login.login_userpost
     *
     * @param loginUserpost the value for sys_login.login_userpost
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public void setLoginUserpost(String loginUserpost) {
        this.loginUserpost = loginUserpost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login.login_userunit
     *
     * @return the value of sys_login.login_userunit
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public String getLoginUserunit() {
        return loginUserunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login.login_userunit
     *
     * @param loginUserunit the value for sys_login.login_userunit
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public void setLoginUserunit(String loginUserunit) {
        this.loginUserunit = loginUserunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login.login_userunitid
     *
     * @return the value of sys_login.login_userunitid
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public String getLoginUserunitid() {
        return loginUserunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login.login_userunitid
     *
     * @param loginUserunitid the value for sys_login.login_userunitid
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public void setLoginUserunitid(String loginUserunitid) {
        this.loginUserunitid = loginUserunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login.login_unitpath
     *
     * @return the value of sys_login.login_unitpath
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public String getLoginUnitpath() {
        return loginUnitpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login.login_unitpath
     *
     * @param loginUnitpath the value for sys_login.login_unitpath
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public void setLoginUnitpath(String loginUnitpath) {
        this.loginUnitpath = loginUnitpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login.login_clientip
     *
     * @return the value of sys_login.login_clientip
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public String getLoginClientip() {
        return loginClientip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login.login_clientip
     *
     * @param loginClientip the value for sys_login.login_clientip
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public void setLoginClientip(String loginClientip) {
        this.loginClientip = loginClientip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login.login_extend
     *
     * @return the value of sys_login.login_extend
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public String getLoginExtend() {
        return loginExtend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login.login_extend
     *
     * @param loginExtend the value for sys_login.login_extend
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public void setLoginExtend(String loginExtend) {
        this.loginExtend = loginExtend;
    }
}