package com.pcitc.base.system;

import java.util.ArrayList;
import java.util.List;

public class SysLoginExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_login
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_login
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_login
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public SysLoginExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_login
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_login
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLoginIdIsNull() {
            addCriterion("login_id is null");
            return (Criteria) this;
        }

        public Criteria andLoginIdIsNotNull() {
            addCriterion("login_id is not null");
            return (Criteria) this;
        }

        public Criteria andLoginIdEqualTo(String value) {
            addCriterion("login_id =", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdNotEqualTo(String value) {
            addCriterion("login_id <>", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdGreaterThan(String value) {
            addCriterion("login_id >", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdGreaterThanOrEqualTo(String value) {
            addCriterion("login_id >=", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdLessThan(String value) {
            addCriterion("login_id <", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdLessThanOrEqualTo(String value) {
            addCriterion("login_id <=", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdLike(String value) {
            addCriterion("login_id like", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdNotLike(String value) {
            addCriterion("login_id not like", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdIn(List<String> values) {
            addCriterion("login_id in", values, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdNotIn(List<String> values) {
            addCriterion("login_id not in", values, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdBetween(String value1, String value2) {
            addCriterion("login_id between", value1, value2, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdNotBetween(String value1, String value2) {
            addCriterion("login_id not between", value1, value2, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginTimeIsNull() {
            addCriterion("login_time is null");
            return (Criteria) this;
        }

        public Criteria andLoginTimeIsNotNull() {
            addCriterion("login_time is not null");
            return (Criteria) this;
        }

        public Criteria andLoginTimeEqualTo(String value) {
            addCriterion("login_time =", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeNotEqualTo(String value) {
            addCriterion("login_time <>", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeGreaterThan(String value) {
            addCriterion("login_time >", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeGreaterThanOrEqualTo(String value) {
            addCriterion("login_time >=", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeLessThan(String value) {
            addCriterion("login_time <", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeLessThanOrEqualTo(String value) {
            addCriterion("login_time <=", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeLike(String value) {
            addCriterion("login_time like", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeNotLike(String value) {
            addCriterion("login_time not like", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeIn(List<String> values) {
            addCriterion("login_time in", values, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeNotIn(List<String> values) {
            addCriterion("login_time not in", values, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeBetween(String value1, String value2) {
            addCriterion("login_time between", value1, value2, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeNotBetween(String value1, String value2) {
            addCriterion("login_time not between", value1, value2, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginUsernameIsNull() {
            addCriterion("login_username is null");
            return (Criteria) this;
        }

        public Criteria andLoginUsernameIsNotNull() {
            addCriterion("login_username is not null");
            return (Criteria) this;
        }

        public Criteria andLoginUsernameEqualTo(String value) {
            addCriterion("login_username =", value, "loginUsername");
            return (Criteria) this;
        }

        public Criteria andLoginUsernameNotEqualTo(String value) {
            addCriterion("login_username <>", value, "loginUsername");
            return (Criteria) this;
        }

        public Criteria andLoginUsernameGreaterThan(String value) {
            addCriterion("login_username >", value, "loginUsername");
            return (Criteria) this;
        }

        public Criteria andLoginUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("login_username >=", value, "loginUsername");
            return (Criteria) this;
        }

        public Criteria andLoginUsernameLessThan(String value) {
            addCriterion("login_username <", value, "loginUsername");
            return (Criteria) this;
        }

        public Criteria andLoginUsernameLessThanOrEqualTo(String value) {
            addCriterion("login_username <=", value, "loginUsername");
            return (Criteria) this;
        }

        public Criteria andLoginUsernameLike(String value) {
            addCriterion("login_username like", value, "loginUsername");
            return (Criteria) this;
        }

        public Criteria andLoginUsernameNotLike(String value) {
            addCriterion("login_username not like", value, "loginUsername");
            return (Criteria) this;
        }

        public Criteria andLoginUsernameIn(List<String> values) {
            addCriterion("login_username in", values, "loginUsername");
            return (Criteria) this;
        }

        public Criteria andLoginUsernameNotIn(List<String> values) {
            addCriterion("login_username not in", values, "loginUsername");
            return (Criteria) this;
        }

        public Criteria andLoginUsernameBetween(String value1, String value2) {
            addCriterion("login_username between", value1, value2, "loginUsername");
            return (Criteria) this;
        }

        public Criteria andLoginUsernameNotBetween(String value1, String value2) {
            addCriterion("login_username not between", value1, value2, "loginUsername");
            return (Criteria) this;
        }

        public Criteria andLoginUserdispIsNull() {
            addCriterion("login_userdisp is null");
            return (Criteria) this;
        }

        public Criteria andLoginUserdispIsNotNull() {
            addCriterion("login_userdisp is not null");
            return (Criteria) this;
        }

        public Criteria andLoginUserdispEqualTo(String value) {
            addCriterion("login_userdisp =", value, "loginUserdisp");
            return (Criteria) this;
        }

        public Criteria andLoginUserdispNotEqualTo(String value) {
            addCriterion("login_userdisp <>", value, "loginUserdisp");
            return (Criteria) this;
        }

        public Criteria andLoginUserdispGreaterThan(String value) {
            addCriterion("login_userdisp >", value, "loginUserdisp");
            return (Criteria) this;
        }

        public Criteria andLoginUserdispGreaterThanOrEqualTo(String value) {
            addCriterion("login_userdisp >=", value, "loginUserdisp");
            return (Criteria) this;
        }

        public Criteria andLoginUserdispLessThan(String value) {
            addCriterion("login_userdisp <", value, "loginUserdisp");
            return (Criteria) this;
        }

        public Criteria andLoginUserdispLessThanOrEqualTo(String value) {
            addCriterion("login_userdisp <=", value, "loginUserdisp");
            return (Criteria) this;
        }

        public Criteria andLoginUserdispLike(String value) {
            addCriterion("login_userdisp like", value, "loginUserdisp");
            return (Criteria) this;
        }

        public Criteria andLoginUserdispNotLike(String value) {
            addCriterion("login_userdisp not like", value, "loginUserdisp");
            return (Criteria) this;
        }

        public Criteria andLoginUserdispIn(List<String> values) {
            addCriterion("login_userdisp in", values, "loginUserdisp");
            return (Criteria) this;
        }

        public Criteria andLoginUserdispNotIn(List<String> values) {
            addCriterion("login_userdisp not in", values, "loginUserdisp");
            return (Criteria) this;
        }

        public Criteria andLoginUserdispBetween(String value1, String value2) {
            addCriterion("login_userdisp between", value1, value2, "loginUserdisp");
            return (Criteria) this;
        }

        public Criteria andLoginUserdispNotBetween(String value1, String value2) {
            addCriterion("login_userdisp not between", value1, value2, "loginUserdisp");
            return (Criteria) this;
        }

        public Criteria andLoginUserpostIsNull() {
            addCriterion("login_userpost is null");
            return (Criteria) this;
        }

        public Criteria andLoginUserpostIsNotNull() {
            addCriterion("login_userpost is not null");
            return (Criteria) this;
        }

        public Criteria andLoginUserpostEqualTo(String value) {
            addCriterion("login_userpost =", value, "loginUserpost");
            return (Criteria) this;
        }

        public Criteria andLoginUserpostNotEqualTo(String value) {
            addCriterion("login_userpost <>", value, "loginUserpost");
            return (Criteria) this;
        }

        public Criteria andLoginUserpostGreaterThan(String value) {
            addCriterion("login_userpost >", value, "loginUserpost");
            return (Criteria) this;
        }

        public Criteria andLoginUserpostGreaterThanOrEqualTo(String value) {
            addCriterion("login_userpost >=", value, "loginUserpost");
            return (Criteria) this;
        }

        public Criteria andLoginUserpostLessThan(String value) {
            addCriterion("login_userpost <", value, "loginUserpost");
            return (Criteria) this;
        }

        public Criteria andLoginUserpostLessThanOrEqualTo(String value) {
            addCriterion("login_userpost <=", value, "loginUserpost");
            return (Criteria) this;
        }

        public Criteria andLoginUserpostLike(String value) {
            addCriterion("login_userpost like", value, "loginUserpost");
            return (Criteria) this;
        }

        public Criteria andLoginUserpostNotLike(String value) {
            addCriterion("login_userpost not like", value, "loginUserpost");
            return (Criteria) this;
        }

        public Criteria andLoginUserpostIn(List<String> values) {
            addCriterion("login_userpost in", values, "loginUserpost");
            return (Criteria) this;
        }

        public Criteria andLoginUserpostNotIn(List<String> values) {
            addCriterion("login_userpost not in", values, "loginUserpost");
            return (Criteria) this;
        }

        public Criteria andLoginUserpostBetween(String value1, String value2) {
            addCriterion("login_userpost between", value1, value2, "loginUserpost");
            return (Criteria) this;
        }

        public Criteria andLoginUserpostNotBetween(String value1, String value2) {
            addCriterion("login_userpost not between", value1, value2, "loginUserpost");
            return (Criteria) this;
        }

        public Criteria andLoginUserunitIsNull() {
            addCriterion("login_userunit is null");
            return (Criteria) this;
        }

        public Criteria andLoginUserunitIsNotNull() {
            addCriterion("login_userunit is not null");
            return (Criteria) this;
        }

        public Criteria andLoginUserunitEqualTo(String value) {
            addCriterion("login_userunit =", value, "loginUserunit");
            return (Criteria) this;
        }

        public Criteria andLoginUserunitNotEqualTo(String value) {
            addCriterion("login_userunit <>", value, "loginUserunit");
            return (Criteria) this;
        }

        public Criteria andLoginUserunitGreaterThan(String value) {
            addCriterion("login_userunit >", value, "loginUserunit");
            return (Criteria) this;
        }

        public Criteria andLoginUserunitGreaterThanOrEqualTo(String value) {
            addCriterion("login_userunit >=", value, "loginUserunit");
            return (Criteria) this;
        }

        public Criteria andLoginUserunitLessThan(String value) {
            addCriterion("login_userunit <", value, "loginUserunit");
            return (Criteria) this;
        }

        public Criteria andLoginUserunitLessThanOrEqualTo(String value) {
            addCriterion("login_userunit <=", value, "loginUserunit");
            return (Criteria) this;
        }

        public Criteria andLoginUserunitLike(String value) {
            addCriterion("login_userunit like", value, "loginUserunit");
            return (Criteria) this;
        }

        public Criteria andLoginUserunitNotLike(String value) {
            addCriterion("login_userunit not like", value, "loginUserunit");
            return (Criteria) this;
        }

        public Criteria andLoginUserunitIn(List<String> values) {
            addCriterion("login_userunit in", values, "loginUserunit");
            return (Criteria) this;
        }

        public Criteria andLoginUserunitNotIn(List<String> values) {
            addCriterion("login_userunit not in", values, "loginUserunit");
            return (Criteria) this;
        }

        public Criteria andLoginUserunitBetween(String value1, String value2) {
            addCriterion("login_userunit between", value1, value2, "loginUserunit");
            return (Criteria) this;
        }

        public Criteria andLoginUserunitNotBetween(String value1, String value2) {
            addCriterion("login_userunit not between", value1, value2, "loginUserunit");
            return (Criteria) this;
        }

        public Criteria andLoginUserunitidIsNull() {
            addCriterion("login_userunitid is null");
            return (Criteria) this;
        }

        public Criteria andLoginUserunitidIsNotNull() {
            addCriterion("login_userunitid is not null");
            return (Criteria) this;
        }

        public Criteria andLoginUserunitidEqualTo(String value) {
            addCriterion("login_userunitid =", value, "loginUserunitid");
            return (Criteria) this;
        }

        public Criteria andLoginUserunitidNotEqualTo(String value) {
            addCriterion("login_userunitid <>", value, "loginUserunitid");
            return (Criteria) this;
        }

        public Criteria andLoginUserunitidGreaterThan(String value) {
            addCriterion("login_userunitid >", value, "loginUserunitid");
            return (Criteria) this;
        }

        public Criteria andLoginUserunitidGreaterThanOrEqualTo(String value) {
            addCriterion("login_userunitid >=", value, "loginUserunitid");
            return (Criteria) this;
        }

        public Criteria andLoginUserunitidLessThan(String value) {
            addCriterion("login_userunitid <", value, "loginUserunitid");
            return (Criteria) this;
        }

        public Criteria andLoginUserunitidLessThanOrEqualTo(String value) {
            addCriterion("login_userunitid <=", value, "loginUserunitid");
            return (Criteria) this;
        }

        public Criteria andLoginUserunitidLike(String value) {
            addCriterion("login_userunitid like", value, "loginUserunitid");
            return (Criteria) this;
        }

        public Criteria andLoginUserunitidNotLike(String value) {
            addCriterion("login_userunitid not like", value, "loginUserunitid");
            return (Criteria) this;
        }

        public Criteria andLoginUserunitidIn(List<String> values) {
            addCriterion("login_userunitid in", values, "loginUserunitid");
            return (Criteria) this;
        }

        public Criteria andLoginUserunitidNotIn(List<String> values) {
            addCriterion("login_userunitid not in", values, "loginUserunitid");
            return (Criteria) this;
        }

        public Criteria andLoginUserunitidBetween(String value1, String value2) {
            addCriterion("login_userunitid between", value1, value2, "loginUserunitid");
            return (Criteria) this;
        }

        public Criteria andLoginUserunitidNotBetween(String value1, String value2) {
            addCriterion("login_userunitid not between", value1, value2, "loginUserunitid");
            return (Criteria) this;
        }

        public Criteria andLoginUnitpathIsNull() {
            addCriterion("login_unitpath is null");
            return (Criteria) this;
        }

        public Criteria andLoginUnitpathIsNotNull() {
            addCriterion("login_unitpath is not null");
            return (Criteria) this;
        }

        public Criteria andLoginUnitpathEqualTo(String value) {
            addCriterion("login_unitpath =", value, "loginUnitpath");
            return (Criteria) this;
        }

        public Criteria andLoginUnitpathNotEqualTo(String value) {
            addCriterion("login_unitpath <>", value, "loginUnitpath");
            return (Criteria) this;
        }

        public Criteria andLoginUnitpathGreaterThan(String value) {
            addCriterion("login_unitpath >", value, "loginUnitpath");
            return (Criteria) this;
        }

        public Criteria andLoginUnitpathGreaterThanOrEqualTo(String value) {
            addCriterion("login_unitpath >=", value, "loginUnitpath");
            return (Criteria) this;
        }

        public Criteria andLoginUnitpathLessThan(String value) {
            addCriterion("login_unitpath <", value, "loginUnitpath");
            return (Criteria) this;
        }

        public Criteria andLoginUnitpathLessThanOrEqualTo(String value) {
            addCriterion("login_unitpath <=", value, "loginUnitpath");
            return (Criteria) this;
        }

        public Criteria andLoginUnitpathLike(String value) {
            addCriterion("login_unitpath like", value, "loginUnitpath");
            return (Criteria) this;
        }

        public Criteria andLoginUnitpathNotLike(String value) {
            addCriterion("login_unitpath not like", value, "loginUnitpath");
            return (Criteria) this;
        }

        public Criteria andLoginUnitpathIn(List<String> values) {
            addCriterion("login_unitpath in", values, "loginUnitpath");
            return (Criteria) this;
        }

        public Criteria andLoginUnitpathNotIn(List<String> values) {
            addCriterion("login_unitpath not in", values, "loginUnitpath");
            return (Criteria) this;
        }

        public Criteria andLoginUnitpathBetween(String value1, String value2) {
            addCriterion("login_unitpath between", value1, value2, "loginUnitpath");
            return (Criteria) this;
        }

        public Criteria andLoginUnitpathNotBetween(String value1, String value2) {
            addCriterion("login_unitpath not between", value1, value2, "loginUnitpath");
            return (Criteria) this;
        }

        public Criteria andLoginClientipIsNull() {
            addCriterion("login_clientip is null");
            return (Criteria) this;
        }

        public Criteria andLoginClientipIsNotNull() {
            addCriterion("login_clientip is not null");
            return (Criteria) this;
        }

        public Criteria andLoginClientipEqualTo(String value) {
            addCriterion("login_clientip =", value, "loginClientip");
            return (Criteria) this;
        }

        public Criteria andLoginClientipNotEqualTo(String value) {
            addCriterion("login_clientip <>", value, "loginClientip");
            return (Criteria) this;
        }

        public Criteria andLoginClientipGreaterThan(String value) {
            addCriterion("login_clientip >", value, "loginClientip");
            return (Criteria) this;
        }

        public Criteria andLoginClientipGreaterThanOrEqualTo(String value) {
            addCriterion("login_clientip >=", value, "loginClientip");
            return (Criteria) this;
        }

        public Criteria andLoginClientipLessThan(String value) {
            addCriterion("login_clientip <", value, "loginClientip");
            return (Criteria) this;
        }

        public Criteria andLoginClientipLessThanOrEqualTo(String value) {
            addCriterion("login_clientip <=", value, "loginClientip");
            return (Criteria) this;
        }

        public Criteria andLoginClientipLike(String value) {
            addCriterion("login_clientip like", value, "loginClientip");
            return (Criteria) this;
        }

        public Criteria andLoginClientipNotLike(String value) {
            addCriterion("login_clientip not like", value, "loginClientip");
            return (Criteria) this;
        }

        public Criteria andLoginClientipIn(List<String> values) {
            addCriterion("login_clientip in", values, "loginClientip");
            return (Criteria) this;
        }

        public Criteria andLoginClientipNotIn(List<String> values) {
            addCriterion("login_clientip not in", values, "loginClientip");
            return (Criteria) this;
        }

        public Criteria andLoginClientipBetween(String value1, String value2) {
            addCriterion("login_clientip between", value1, value2, "loginClientip");
            return (Criteria) this;
        }

        public Criteria andLoginClientipNotBetween(String value1, String value2) {
            addCriterion("login_clientip not between", value1, value2, "loginClientip");
            return (Criteria) this;
        }

        public Criteria andLoginExtendIsNull() {
            addCriterion("login_extend is null");
            return (Criteria) this;
        }

        public Criteria andLoginExtendIsNotNull() {
            addCriterion("login_extend is not null");
            return (Criteria) this;
        }

        public Criteria andLoginExtendEqualTo(String value) {
            addCriterion("login_extend =", value, "loginExtend");
            return (Criteria) this;
        }

        public Criteria andLoginExtendNotEqualTo(String value) {
            addCriterion("login_extend <>", value, "loginExtend");
            return (Criteria) this;
        }

        public Criteria andLoginExtendGreaterThan(String value) {
            addCriterion("login_extend >", value, "loginExtend");
            return (Criteria) this;
        }

        public Criteria andLoginExtendGreaterThanOrEqualTo(String value) {
            addCriterion("login_extend >=", value, "loginExtend");
            return (Criteria) this;
        }

        public Criteria andLoginExtendLessThan(String value) {
            addCriterion("login_extend <", value, "loginExtend");
            return (Criteria) this;
        }

        public Criteria andLoginExtendLessThanOrEqualTo(String value) {
            addCriterion("login_extend <=", value, "loginExtend");
            return (Criteria) this;
        }

        public Criteria andLoginExtendLike(String value) {
            addCriterion("login_extend like", value, "loginExtend");
            return (Criteria) this;
        }

        public Criteria andLoginExtendNotLike(String value) {
            addCriterion("login_extend not like", value, "loginExtend");
            return (Criteria) this;
        }

        public Criteria andLoginExtendIn(List<String> values) {
            addCriterion("login_extend in", values, "loginExtend");
            return (Criteria) this;
        }

        public Criteria andLoginExtendNotIn(List<String> values) {
            addCriterion("login_extend not in", values, "loginExtend");
            return (Criteria) this;
        }

        public Criteria andLoginExtendBetween(String value1, String value2) {
            addCriterion("login_extend between", value1, value2, "loginExtend");
            return (Criteria) this;
        }

        public Criteria andLoginExtendNotBetween(String value1, String value2) {
            addCriterion("login_extend not between", value1, value2, "loginExtend");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_login
     *
     * @mbg.generated do_not_delete_during_merge Fri Apr 13 16:40:44 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_login
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}