package com.pcitc.base.system;

public class SysPostFunction {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_post_function.rel_id
	 * @mbg.generated  Wed Jun 20 16:42:28 CST 2018
	 */
	private String relId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_post_function.unit_id
	 * @mbg.generated  Wed Jun 20 16:42:28 CST 2018
	 */
	private String unitId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_post_function.unit_code
	 * @mbg.generated  Wed Jun 20 16:42:28 CST 2018
	 */
	private String unitCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_post_function.post_id
	 * @mbg.generated  Wed Jun 20 16:42:28 CST 2018
	 */
	private String postId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_post_function.post_code
	 * @mbg.generated  Wed Jun 20 16:42:28 CST 2018
	 */
	private String postCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_post_function.function_id
	 * @mbg.generated  Wed Jun 20 16:42:28 CST 2018
	 */
	private String functionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_post_function.function_code
	 * @mbg.generated  Wed Jun 20 16:42:28 CST 2018
	 */
	private String functionCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_post_function.function_buttons
	 * @mbg.generated  Wed Jun 20 16:42:28 CST 2018
	 */
	private String functionButtons;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_post_function.create_person_id
	 * @mbg.generated  Wed Jun 20 16:42:28 CST 2018
	 */
	private String createPersonId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_post_function.create_date
	 * @mbg.generated  Wed Jun 20 16:42:28 CST 2018
	 */
	private String createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_post_function.remarks
	 * @mbg.generated  Wed Jun 20 16:42:28 CST 2018
	 */
	private String remarks;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_post_function.rel_id
	 * @return  the value of sys_post_function.rel_id
	 * @mbg.generated  Wed Jun 20 16:42:28 CST 2018
	 */
	public String getRelId() {
		return relId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_post_function.rel_id
	 * @param relId  the value for sys_post_function.rel_id
	 * @mbg.generated  Wed Jun 20 16:42:28 CST 2018
	 */
	public void setRelId(String relId) {
		this.relId = relId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_post_function.unit_id
	 * @return  the value of sys_post_function.unit_id
	 * @mbg.generated  Wed Jun 20 16:42:28 CST 2018
	 */
	public String getUnitId() {
		return unitId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_post_function.unit_id
	 * @param unitId  the value for sys_post_function.unit_id
	 * @mbg.generated  Wed Jun 20 16:42:28 CST 2018
	 */
	public void setUnitId(String unitId) {
		this.unitId = unitId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_post_function.unit_code
	 * @return  the value of sys_post_function.unit_code
	 * @mbg.generated  Wed Jun 20 16:42:28 CST 2018
	 */
	public String getUnitCode() {
		return unitCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_post_function.unit_code
	 * @param unitCode  the value for sys_post_function.unit_code
	 * @mbg.generated  Wed Jun 20 16:42:28 CST 2018
	 */
	public void setUnitCode(String unitCode) {
		this.unitCode = unitCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_post_function.post_id
	 * @return  the value of sys_post_function.post_id
	 * @mbg.generated  Wed Jun 20 16:42:28 CST 2018
	 */
	public String getPostId() {
		return postId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_post_function.post_id
	 * @param postId  the value for sys_post_function.post_id
	 * @mbg.generated  Wed Jun 20 16:42:28 CST 2018
	 */
	public void setPostId(String postId) {
		this.postId = postId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_post_function.post_code
	 * @return  the value of sys_post_function.post_code
	 * @mbg.generated  Wed Jun 20 16:42:28 CST 2018
	 */
	public String getPostCode() {
		return postCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_post_function.post_code
	 * @param postCode  the value for sys_post_function.post_code
	 * @mbg.generated  Wed Jun 20 16:42:28 CST 2018
	 */
	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_post_function.function_id
	 * @return  the value of sys_post_function.function_id
	 * @mbg.generated  Wed Jun 20 16:42:28 CST 2018
	 */
	public String getFunctionId() {
		return functionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_post_function.function_id
	 * @param functionId  the value for sys_post_function.function_id
	 * @mbg.generated  Wed Jun 20 16:42:28 CST 2018
	 */
	public void setFunctionId(String functionId) {
		this.functionId = functionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_post_function.function_code
	 * @return  the value of sys_post_function.function_code
	 * @mbg.generated  Wed Jun 20 16:42:28 CST 2018
	 */
	public String getFunctionCode() {
		return functionCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_post_function.function_code
	 * @param functionCode  the value for sys_post_function.function_code
	 * @mbg.generated  Wed Jun 20 16:42:28 CST 2018
	 */
	public void setFunctionCode(String functionCode) {
		this.functionCode = functionCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_post_function.function_buttons
	 * @return  the value of sys_post_function.function_buttons
	 * @mbg.generated  Wed Jun 20 16:42:28 CST 2018
	 */
	public String getFunctionButtons() {
		return functionButtons;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_post_function.function_buttons
	 * @param functionButtons  the value for sys_post_function.function_buttons
	 * @mbg.generated  Wed Jun 20 16:42:28 CST 2018
	 */
	public void setFunctionButtons(String functionButtons) {
		this.functionButtons = functionButtons;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_post_function.create_person_id
	 * @return  the value of sys_post_function.create_person_id
	 * @mbg.generated  Wed Jun 20 16:42:28 CST 2018
	 */
	public String getCreatePersonId() {
		return createPersonId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_post_function.create_person_id
	 * @param createPersonId  the value for sys_post_function.create_person_id
	 * @mbg.generated  Wed Jun 20 16:42:28 CST 2018
	 */
	public void setCreatePersonId(String createPersonId) {
		this.createPersonId = createPersonId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_post_function.create_date
	 * @return  the value of sys_post_function.create_date
	 * @mbg.generated  Wed Jun 20 16:42:28 CST 2018
	 */
	public String getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_post_function.create_date
	 * @param createDate  the value for sys_post_function.create_date
	 * @mbg.generated  Wed Jun 20 16:42:28 CST 2018
	 */
	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_post_function.remarks
	 * @return  the value of sys_post_function.remarks
	 * @mbg.generated  Wed Jun 20 16:42:28 CST 2018
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_post_function.remarks
	 * @param remarks  the value for sys_post_function.remarks
	 * @mbg.generated  Wed Jun 20 16:42:28 CST 2018
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}
}