package com.pcitc.base.system;

public class SysPost {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_post.post_id
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	private String postId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_post.post_name
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	private String postName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_post.post_code
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	private String postCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_post.post_flag
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	private String postFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_post.post_kind
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	private String postKind;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_post.create_date
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	private String createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_post.create_person_id
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	private String createPersonId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_post.post_extend
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	private String postExtend;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_post.post_order
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	private Integer postOrder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_post.post_comment
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	private String postComment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_post.post_delflag
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	private Integer postDelflag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_post.post_level
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	private Integer postLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_post.post_relation
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	private String postRelation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_post.post_unit
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	private String postUnit;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_post.post_id
	 * @return  the value of sys_post.post_id
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	public String getPostId() {
		return postId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_post.post_id
	 * @param postId  the value for sys_post.post_id
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	public void setPostId(String postId) {
		this.postId = postId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_post.post_name
	 * @return  the value of sys_post.post_name
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	public String getPostName() {
		return postName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_post.post_name
	 * @param postName  the value for sys_post.post_name
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	public void setPostName(String postName) {
		this.postName = postName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_post.post_code
	 * @return  the value of sys_post.post_code
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	public String getPostCode() {
		return postCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_post.post_code
	 * @param postCode  the value for sys_post.post_code
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_post.post_flag
	 * @return  the value of sys_post.post_flag
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	public String getPostFlag() {
		return postFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_post.post_flag
	 * @param postFlag  the value for sys_post.post_flag
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	public void setPostFlag(String postFlag) {
		this.postFlag = postFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_post.post_kind
	 * @return  the value of sys_post.post_kind
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	public String getPostKind() {
		return postKind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_post.post_kind
	 * @param postKind  the value for sys_post.post_kind
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	public void setPostKind(String postKind) {
		this.postKind = postKind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_post.create_date
	 * @return  the value of sys_post.create_date
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	public String getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_post.create_date
	 * @param createDate  the value for sys_post.create_date
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_post.create_person_id
	 * @return  the value of sys_post.create_person_id
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	public String getCreatePersonId() {
		return createPersonId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_post.create_person_id
	 * @param createPersonId  the value for sys_post.create_person_id
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	public void setCreatePersonId(String createPersonId) {
		this.createPersonId = createPersonId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_post.post_extend
	 * @return  the value of sys_post.post_extend
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	public String getPostExtend() {
		return postExtend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_post.post_extend
	 * @param postExtend  the value for sys_post.post_extend
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	public void setPostExtend(String postExtend) {
		this.postExtend = postExtend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_post.post_order
	 * @return  the value of sys_post.post_order
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	public Integer getPostOrder() {
		return postOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_post.post_order
	 * @param postOrder  the value for sys_post.post_order
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	public void setPostOrder(Integer postOrder) {
		this.postOrder = postOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_post.post_comment
	 * @return  the value of sys_post.post_comment
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	public String getPostComment() {
		return postComment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_post.post_comment
	 * @param postComment  the value for sys_post.post_comment
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	public void setPostComment(String postComment) {
		this.postComment = postComment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_post.post_delflag
	 * @return  the value of sys_post.post_delflag
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	public Integer getPostDelflag() {
		return postDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_post.post_delflag
	 * @param postDelflag  the value for sys_post.post_delflag
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	public void setPostDelflag(Integer postDelflag) {
		this.postDelflag = postDelflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_post.post_level
	 * @return  the value of sys_post.post_level
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	public Integer getPostLevel() {
		return postLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_post.post_level
	 * @param postLevel  the value for sys_post.post_level
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	public void setPostLevel(Integer postLevel) {
		this.postLevel = postLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_post.post_relation
	 * @return  the value of sys_post.post_relation
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	public String getPostRelation() {
		return postRelation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_post.post_relation
	 * @param postRelation  the value for sys_post.post_relation
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	public void setPostRelation(String postRelation) {
		this.postRelation = postRelation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_post.post_unit
	 * @return  the value of sys_post.post_unit
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	public String getPostUnit() {
		return postUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_post.post_unit
	 * @param postUnit  the value for sys_post.post_unit
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	public void setPostUnit(String postUnit) {
		this.postUnit = postUnit;
	}
}