package com.pcitc.mapper.system;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.pcitc.base.system.SysRoleFunction;
import com.pcitc.base.system.SysRoleFunctionExample;

public interface SysRoleFunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function
     *
     * @mbg.generated Wed Apr 18 13:18:39 CST 2018
     */
    long countByExample(SysRoleFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function
     *
     * @mbg.generated Wed Apr 18 13:18:39 CST 2018
     */
    int deleteByExample(SysRoleFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function
     *
     * @mbg.generated Wed Apr 18 13:18:39 CST 2018
     */
    int deleteByPrimaryKey(String relId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function
     *
     * @mbg.generated Wed Apr 18 13:18:39 CST 2018
     */
    int insert(SysRoleFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function
     *
     * @mbg.generated Wed Apr 18 13:18:39 CST 2018
     */
    int insertSelective(SysRoleFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function
     *
     * @mbg.generated Wed Apr 18 13:18:39 CST 2018
     */
    List<SysRoleFunction> selectByExample(SysRoleFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function
     *
     * @mbg.generated Wed Apr 18 13:18:39 CST 2018
     */
    SysRoleFunction selectByPrimaryKey(String relId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function
     *
     * @mbg.generated Wed Apr 18 13:18:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysRoleFunction record, @Param("example") SysRoleFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function
     *
     * @mbg.generated Wed Apr 18 13:18:39 CST 2018
     */
    int updateByExample(@Param("record") SysRoleFunction record, @Param("example") SysRoleFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function
     *
     * @mbg.generated Wed Apr 18 13:18:39 CST 2018
     */
    int updateByPrimaryKeySelective(SysRoleFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function
     *
     * @mbg.generated Wed Apr 18 13:18:39 CST 2018
     */
    int updateByPrimaryKey(SysRoleFunction record);
}