package com.pcitc.base.engin.hse.personnel;

import java.io.Serializable;

import com.pcitc.base.util.SearchInfo;

public class PersonnelInfoDetail extends SearchInfo  implements Serializable{
	
	private static final long serialVersionUID = 1L;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hse_personnel_info_detail.data_id
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	private String dataId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hse_personnel_info_detail.create_user
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hse_personnel_info_detail.create_date
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	private String createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hse_personnel_info_detail.update_user
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	private String updateUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hse_personnel_info_detail.update_date
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	private String updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hse_personnel_info_detail.status
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hse_personnel_info_detail.audit_status
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	private String auditStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hse_personnel_info_detail.company_code
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	private String companyCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hse_personnel_info_detail.project_id
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	private String projectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hse_personnel_info_detail.form_code
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	private String formCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hse_personnel_info_detail.profession
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	private String profession;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hse_personnel_info_detail.qualification_type
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	private String qualificationType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hse_personnel_info_detail.profession_type
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	private String professionType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hse_personnel_info_detail.qualification_name
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	private String qualificationName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hse_personnel_info_detail.level
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	private String level;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hse_personnel_info_detail.certificate_number
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	private String certificateNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hse_personnel_info_detail.certification_date
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	private String certificationDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hse_personnel_info_detail.expiration_date
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	private String expirationDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hse_personnel_info_detail.issuing_unit
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	private String issuingUnit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hse_personnel_info_detail.qualified_project
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	private String qualifiedProject;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hse_personnel_info_detail.check_method
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	private String checkMethod;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hse_personnel_info_detail.personnel_id
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	private String personnelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hse_personnel_info_detail.attach_id
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	private String attachId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hse_personnel_info_detail.data_id
	 * @return  the value of hse_personnel_info_detail.data_id
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public String getDataId() {
		return dataId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hse_personnel_info_detail.data_id
	 * @param dataId  the value for hse_personnel_info_detail.data_id
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public void setDataId(String dataId) {
		this.dataId = dataId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hse_personnel_info_detail.create_user
	 * @return  the value of hse_personnel_info_detail.create_user
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hse_personnel_info_detail.create_user
	 * @param createUser  the value for hse_personnel_info_detail.create_user
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hse_personnel_info_detail.create_date
	 * @return  the value of hse_personnel_info_detail.create_date
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public String getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hse_personnel_info_detail.create_date
	 * @param createDate  the value for hse_personnel_info_detail.create_date
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hse_personnel_info_detail.update_user
	 * @return  the value of hse_personnel_info_detail.update_user
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hse_personnel_info_detail.update_user
	 * @param updateUser  the value for hse_personnel_info_detail.update_user
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hse_personnel_info_detail.update_date
	 * @return  the value of hse_personnel_info_detail.update_date
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public String getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hse_personnel_info_detail.update_date
	 * @param updateDate  the value for hse_personnel_info_detail.update_date
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public void setUpdateDate(String updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hse_personnel_info_detail.status
	 * @return  the value of hse_personnel_info_detail.status
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hse_personnel_info_detail.status
	 * @param status  the value for hse_personnel_info_detail.status
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hse_personnel_info_detail.audit_status
	 * @return  the value of hse_personnel_info_detail.audit_status
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public String getAuditStatus() {
		return auditStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hse_personnel_info_detail.audit_status
	 * @param auditStatus  the value for hse_personnel_info_detail.audit_status
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public void setAuditStatus(String auditStatus) {
		this.auditStatus = auditStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hse_personnel_info_detail.company_code
	 * @return  the value of hse_personnel_info_detail.company_code
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public String getCompanyCode() {
		return companyCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hse_personnel_info_detail.company_code
	 * @param companyCode  the value for hse_personnel_info_detail.company_code
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hse_personnel_info_detail.project_id
	 * @return  the value of hse_personnel_info_detail.project_id
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public String getProjectId() {
		return projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hse_personnel_info_detail.project_id
	 * @param projectId  the value for hse_personnel_info_detail.project_id
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hse_personnel_info_detail.form_code
	 * @return  the value of hse_personnel_info_detail.form_code
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public String getFormCode() {
		return formCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hse_personnel_info_detail.form_code
	 * @param formCode  the value for hse_personnel_info_detail.form_code
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public void setFormCode(String formCode) {
		this.formCode = formCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hse_personnel_info_detail.profession
	 * @return  the value of hse_personnel_info_detail.profession
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public String getProfession() {
		return profession;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hse_personnel_info_detail.profession
	 * @param profession  the value for hse_personnel_info_detail.profession
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public void setProfession(String profession) {
		this.profession = profession;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hse_personnel_info_detail.qualification_type
	 * @return  the value of hse_personnel_info_detail.qualification_type
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public String getQualificationType() {
		return qualificationType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hse_personnel_info_detail.qualification_type
	 * @param qualificationType  the value for hse_personnel_info_detail.qualification_type
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public void setQualificationType(String qualificationType) {
		this.qualificationType = qualificationType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hse_personnel_info_detail.profession_type
	 * @return  the value of hse_personnel_info_detail.profession_type
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public String getProfessionType() {
		return professionType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hse_personnel_info_detail.profession_type
	 * @param professionType  the value for hse_personnel_info_detail.profession_type
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public void setProfessionType(String professionType) {
		this.professionType = professionType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hse_personnel_info_detail.qualification_name
	 * @return  the value of hse_personnel_info_detail.qualification_name
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public String getQualificationName() {
		return qualificationName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hse_personnel_info_detail.qualification_name
	 * @param qualificationName  the value for hse_personnel_info_detail.qualification_name
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public void setQualificationName(String qualificationName) {
		this.qualificationName = qualificationName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hse_personnel_info_detail.level
	 * @return  the value of hse_personnel_info_detail.level
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public String getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hse_personnel_info_detail.level
	 * @param level  the value for hse_personnel_info_detail.level
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public void setLevel(String level) {
		this.level = level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hse_personnel_info_detail.certificate_number
	 * @return  the value of hse_personnel_info_detail.certificate_number
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public String getCertificateNumber() {
		return certificateNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hse_personnel_info_detail.certificate_number
	 * @param certificateNumber  the value for hse_personnel_info_detail.certificate_number
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public void setCertificateNumber(String certificateNumber) {
		this.certificateNumber = certificateNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hse_personnel_info_detail.certification_date
	 * @return  the value of hse_personnel_info_detail.certification_date
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public String getCertificationDate() {
		return certificationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hse_personnel_info_detail.certification_date
	 * @param certificationDate  the value for hse_personnel_info_detail.certification_date
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public void setCertificationDate(String certificationDate) {
		this.certificationDate = certificationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hse_personnel_info_detail.expiration_date
	 * @return  the value of hse_personnel_info_detail.expiration_date
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public String getExpirationDate() {
		return expirationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hse_personnel_info_detail.expiration_date
	 * @param expirationDate  the value for hse_personnel_info_detail.expiration_date
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public void setExpirationDate(String expirationDate) {
		this.expirationDate = expirationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hse_personnel_info_detail.issuing_unit
	 * @return  the value of hse_personnel_info_detail.issuing_unit
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public String getIssuingUnit() {
		return issuingUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hse_personnel_info_detail.issuing_unit
	 * @param issuingUnit  the value for hse_personnel_info_detail.issuing_unit
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public void setIssuingUnit(String issuingUnit) {
		this.issuingUnit = issuingUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hse_personnel_info_detail.qualified_project
	 * @return  the value of hse_personnel_info_detail.qualified_project
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public String getQualifiedProject() {
		return qualifiedProject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hse_personnel_info_detail.qualified_project
	 * @param qualifiedProject  the value for hse_personnel_info_detail.qualified_project
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public void setQualifiedProject(String qualifiedProject) {
		this.qualifiedProject = qualifiedProject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hse_personnel_info_detail.check_method
	 * @return  the value of hse_personnel_info_detail.check_method
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public String getCheckMethod() {
		return checkMethod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hse_personnel_info_detail.check_method
	 * @param checkMethod  the value for hse_personnel_info_detail.check_method
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public void setCheckMethod(String checkMethod) {
		this.checkMethod = checkMethod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hse_personnel_info_detail.personnel_id
	 * @return  the value of hse_personnel_info_detail.personnel_id
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public String getPersonnelId() {
		return personnelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hse_personnel_info_detail.personnel_id
	 * @param personnelId  the value for hse_personnel_info_detail.personnel_id
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public void setPersonnelId(String personnelId) {
		this.personnelId = personnelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hse_personnel_info_detail.attach_id
	 * @return  the value of hse_personnel_info_detail.attach_id
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public String getAttachId() {
		return attachId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hse_personnel_info_detail.attach_id
	 * @param attachId  the value for hse_personnel_info_detail.attach_id
	 * @mbggenerated  Wed Aug 15 11:21:33 CST 2018
	 */
	public void setAttachId(String attachId) {
		this.attachId = attachId;
	}

}