package com.pcitc.base.engin.prophase;

public class Eps {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epms_eps.data_id
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    private String dataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epms_eps.create_user
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epms_eps.create_date
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epms_eps.update_user
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epms_eps.update_date
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epms_eps.status
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epms_eps.audit_status
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    private String auditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epms_eps.company_code
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    private String companyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epms_eps.project_id
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    private String projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epms_eps.form_code
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    private String formCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epms_eps.eps_name
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    private String epsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epms_eps.eps_code
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    private String epsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epms_eps.eps_path
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    private String epsPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epms_eps.eps_relation
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    private String epsRelation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epms_eps.eps_level
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    private String epsLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epms_eps.remark
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epms_eps.data_id
     *
     * @return the value of epms_eps.data_id
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    public String getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epms_eps.data_id
     *
     * @param dataId the value for epms_eps.data_id
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    public void setDataId(String dataId) {
        this.dataId = dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epms_eps.create_user
     *
     * @return the value of epms_eps.create_user
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epms_eps.create_user
     *
     * @param createUser the value for epms_eps.create_user
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epms_eps.create_date
     *
     * @return the value of epms_eps.create_date
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epms_eps.create_date
     *
     * @param createDate the value for epms_eps.create_date
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epms_eps.update_user
     *
     * @return the value of epms_eps.update_user
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epms_eps.update_user
     *
     * @param updateUser the value for epms_eps.update_user
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epms_eps.update_date
     *
     * @return the value of epms_eps.update_date
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epms_eps.update_date
     *
     * @param updateDate the value for epms_eps.update_date
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epms_eps.status
     *
     * @return the value of epms_eps.status
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epms_eps.status
     *
     * @param status the value for epms_eps.status
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epms_eps.audit_status
     *
     * @return the value of epms_eps.audit_status
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    public String getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epms_eps.audit_status
     *
     * @param auditStatus the value for epms_eps.audit_status
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    public void setAuditStatus(String auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epms_eps.company_code
     *
     * @return the value of epms_eps.company_code
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epms_eps.company_code
     *
     * @param companyCode the value for epms_eps.company_code
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epms_eps.project_id
     *
     * @return the value of epms_eps.project_id
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epms_eps.project_id
     *
     * @param projectId the value for epms_eps.project_id
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epms_eps.form_code
     *
     * @return the value of epms_eps.form_code
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    public String getFormCode() {
        return formCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epms_eps.form_code
     *
     * @param formCode the value for epms_eps.form_code
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    public void setFormCode(String formCode) {
        this.formCode = formCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epms_eps.eps_name
     *
     * @return the value of epms_eps.eps_name
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    public String getEpsName() {
        return epsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epms_eps.eps_name
     *
     * @param epsName the value for epms_eps.eps_name
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    public void setEpsName(String epsName) {
        this.epsName = epsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epms_eps.eps_code
     *
     * @return the value of epms_eps.eps_code
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    public String getEpsCode() {
        return epsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epms_eps.eps_code
     *
     * @param epsCode the value for epms_eps.eps_code
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    public void setEpsCode(String epsCode) {
        this.epsCode = epsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epms_eps.eps_path
     *
     * @return the value of epms_eps.eps_path
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    public String getEpsPath() {
        return epsPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epms_eps.eps_path
     *
     * @param epsPath the value for epms_eps.eps_path
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    public void setEpsPath(String epsPath) {
        this.epsPath = epsPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epms_eps.eps_relation
     *
     * @return the value of epms_eps.eps_relation
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    public String getEpsRelation() {
        return epsRelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epms_eps.eps_relation
     *
     * @param epsRelation the value for epms_eps.eps_relation
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    public void setEpsRelation(String epsRelation) {
        this.epsRelation = epsRelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epms_eps.eps_level
     *
     * @return the value of epms_eps.eps_level
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    public String getEpsLevel() {
        return epsLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epms_eps.eps_level
     *
     * @param epsLevel the value for epms_eps.eps_level
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    public void setEpsLevel(String epsLevel) {
        this.epsLevel = epsLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epms_eps.remark
     *
     * @return the value of epms_eps.remark
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epms_eps.remark
     *
     * @param remark the value for epms_eps.remark
     *
     * @mbggenerated Mon Oct 22 16:40:55 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}