package com.pcitc.base.engin.pub;

public class MaterialClassify {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_material_classify.data_id
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    private String dataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_material_classify.create_user
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_material_classify.create_date
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_material_classify.update_user
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_material_classify.update_date
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_material_classify.status
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_material_classify.audit_status
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    private String auditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_material_classify.company_code
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    private String companyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_material_classify.project_id
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    private String projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_material_classify.form_code
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    private String formCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_material_classify.classify_name
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    private String classifyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_material_classify.classify_code
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    private String classifyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_material_classify.classify_level
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    private String classifyLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_material_classify.parent_id
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_material_classify.metering_unit
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    private String meteringUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_material_classify.subnode
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    private String subnode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_material_classify.remark
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_material_classify.data_id
     *
     * @return the value of pub_material_classify.data_id
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    public String getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_material_classify.data_id
     *
     * @param dataId the value for pub_material_classify.data_id
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    public void setDataId(String dataId) {
        this.dataId = dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_material_classify.create_user
     *
     * @return the value of pub_material_classify.create_user
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_material_classify.create_user
     *
     * @param createUser the value for pub_material_classify.create_user
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_material_classify.create_date
     *
     * @return the value of pub_material_classify.create_date
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_material_classify.create_date
     *
     * @param createDate the value for pub_material_classify.create_date
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_material_classify.update_user
     *
     * @return the value of pub_material_classify.update_user
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_material_classify.update_user
     *
     * @param updateUser the value for pub_material_classify.update_user
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_material_classify.update_date
     *
     * @return the value of pub_material_classify.update_date
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_material_classify.update_date
     *
     * @param updateDate the value for pub_material_classify.update_date
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_material_classify.status
     *
     * @return the value of pub_material_classify.status
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_material_classify.status
     *
     * @param status the value for pub_material_classify.status
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_material_classify.audit_status
     *
     * @return the value of pub_material_classify.audit_status
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    public String getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_material_classify.audit_status
     *
     * @param auditStatus the value for pub_material_classify.audit_status
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    public void setAuditStatus(String auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_material_classify.company_code
     *
     * @return the value of pub_material_classify.company_code
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_material_classify.company_code
     *
     * @param companyCode the value for pub_material_classify.company_code
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_material_classify.project_id
     *
     * @return the value of pub_material_classify.project_id
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_material_classify.project_id
     *
     * @param projectId the value for pub_material_classify.project_id
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_material_classify.form_code
     *
     * @return the value of pub_material_classify.form_code
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    public String getFormCode() {
        return formCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_material_classify.form_code
     *
     * @param formCode the value for pub_material_classify.form_code
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    public void setFormCode(String formCode) {
        this.formCode = formCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_material_classify.classify_name
     *
     * @return the value of pub_material_classify.classify_name
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    public String getClassifyName() {
        return classifyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_material_classify.classify_name
     *
     * @param classifyName the value for pub_material_classify.classify_name
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    public void setClassifyName(String classifyName) {
        this.classifyName = classifyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_material_classify.classify_code
     *
     * @return the value of pub_material_classify.classify_code
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    public String getClassifyCode() {
        return classifyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_material_classify.classify_code
     *
     * @param classifyCode the value for pub_material_classify.classify_code
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    public void setClassifyCode(String classifyCode) {
        this.classifyCode = classifyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_material_classify.classify_level
     *
     * @return the value of pub_material_classify.classify_level
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    public String getClassifyLevel() {
        return classifyLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_material_classify.classify_level
     *
     * @param classifyLevel the value for pub_material_classify.classify_level
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    public void setClassifyLevel(String classifyLevel) {
        this.classifyLevel = classifyLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_material_classify.parent_id
     *
     * @return the value of pub_material_classify.parent_id
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_material_classify.parent_id
     *
     * @param parentId the value for pub_material_classify.parent_id
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_material_classify.metering_unit
     *
     * @return the value of pub_material_classify.metering_unit
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    public String getMeteringUnit() {
        return meteringUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_material_classify.metering_unit
     *
     * @param meteringUnit the value for pub_material_classify.metering_unit
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    public void setMeteringUnit(String meteringUnit) {
        this.meteringUnit = meteringUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_material_classify.subnode
     *
     * @return the value of pub_material_classify.subnode
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    public String getSubnode() {
        return subnode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_material_classify.subnode
     *
     * @param subnode the value for pub_material_classify.subnode
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    public void setSubnode(String subnode) {
        this.subnode = subnode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_material_classify.remark
     *
     * @return the value of pub_material_classify.remark
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_material_classify.remark
     *
     * @param remark the value for pub_material_classify.remark
     *
     * @mbggenerated Mon Oct 15 15:35:28 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}