package com.pcitc.mapper.system;

import com.pcitc.base.system.SysFunctionGroup;
import com.pcitc.base.system.SysFunctionGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysFunctionGroupMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_function_group
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	long countByExample(SysFunctionGroupExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_function_group
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	int deleteByExample(SysFunctionGroupExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_function_group
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	int deleteByPrimaryKey(String groupId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_function_group
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	int insert(SysFunctionGroup record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_function_group
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	int insertSelective(SysFunctionGroup record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_function_group
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	List<SysFunctionGroup> selectByExample(SysFunctionGroupExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_function_group
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	SysFunctionGroup selectByPrimaryKey(String groupId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_function_group
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	int updateByExampleSelective(@Param("record") SysFunctionGroup record,
			@Param("example") SysFunctionGroupExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_function_group
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	int updateByExample(@Param("record") SysFunctionGroup record, @Param("example") SysFunctionGroupExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_function_group
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	int updateByPrimaryKeySelective(SysFunctionGroup record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_function_group
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	int updateByPrimaryKey(SysFunctionGroup record);
}