package com.pcitc.mapper.system;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.pcitc.base.system.SysPost;
import com.pcitc.base.system.SysPostExample;

public interface SysPostMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_post
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	long countByExample(SysPostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_post
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	int deleteByExample(SysPostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_post
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	int deleteByPrimaryKey(String postId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_post
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	int insert(SysPost record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_post
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	int insertSelective(SysPost record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_post
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	List<SysPost> selectByExample(SysPostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_post
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	SysPost selectByPrimaryKey(String postId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_post
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	int updateByExampleSelective(@Param("record") SysPost record, @Param("example") SysPostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_post
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	int updateByExample(@Param("record") SysPost record, @Param("example") SysPostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_post
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	int updateByPrimaryKeySelective(SysPost record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_post
	 * @mbg.generated  Wed Jun 13 09:17:02 CST 2018
	 */
	int updateByPrimaryKey(SysPost record);
}