package com.pcitc.base.engin.hse.training;

import java.io.Serializable;

import com.pcitc.base.util.SearchInfo;

public class TrainingPlan extends SearchInfo  implements Serializable{
	
	private static final long serialVersionUID = 1L;
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_plan.data_id
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    private String dataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_plan.create_user
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_plan.create_date
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_plan.update_user
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_plan.update_date
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_plan.status
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_plan.audit_status
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    private String auditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_plan.company_code
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    private String companyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_plan.project_id
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    private String projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_plan.form_code
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    private String formCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_plan.type
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_plan.preiod
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    private String preiod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_plan.phone
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_plan.address
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_plan.number
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_plan.surplus_number
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    private String surplusNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_plan.time
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_plan.attach_id
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    private String attachId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_plan.remarks
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_plan.data_id
     *
     * @return the value of hse_training_plan.data_id
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public String getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_plan.data_id
     *
     * @param dataId the value for hse_training_plan.data_id
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public void setDataId(String dataId) {
        this.dataId = dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_plan.create_user
     *
     * @return the value of hse_training_plan.create_user
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_plan.create_user
     *
     * @param createUser the value for hse_training_plan.create_user
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_plan.create_date
     *
     * @return the value of hse_training_plan.create_date
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_plan.create_date
     *
     * @param createDate the value for hse_training_plan.create_date
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_plan.update_user
     *
     * @return the value of hse_training_plan.update_user
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_plan.update_user
     *
     * @param updateUser the value for hse_training_plan.update_user
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_plan.update_date
     *
     * @return the value of hse_training_plan.update_date
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_plan.update_date
     *
     * @param updateDate the value for hse_training_plan.update_date
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_plan.status
     *
     * @return the value of hse_training_plan.status
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_plan.status
     *
     * @param status the value for hse_training_plan.status
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_plan.audit_status
     *
     * @return the value of hse_training_plan.audit_status
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public String getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_plan.audit_status
     *
     * @param auditStatus the value for hse_training_plan.audit_status
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public void setAuditStatus(String auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_plan.company_code
     *
     * @return the value of hse_training_plan.company_code
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_plan.company_code
     *
     * @param companyCode the value for hse_training_plan.company_code
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_plan.project_id
     *
     * @return the value of hse_training_plan.project_id
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_plan.project_id
     *
     * @param projectId the value for hse_training_plan.project_id
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_plan.form_code
     *
     * @return the value of hse_training_plan.form_code
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public String getFormCode() {
        return formCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_plan.form_code
     *
     * @param formCode the value for hse_training_plan.form_code
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public void setFormCode(String formCode) {
        this.formCode = formCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_plan.type
     *
     * @return the value of hse_training_plan.type
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_plan.type
     *
     * @param type the value for hse_training_plan.type
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_plan.preiod
     *
     * @return the value of hse_training_plan.preiod
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public String getPreiod() {
        return preiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_plan.preiod
     *
     * @param preiod the value for hse_training_plan.preiod
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public void setPreiod(String preiod) {
        this.preiod = preiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_plan.phone
     *
     * @return the value of hse_training_plan.phone
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_plan.phone
     *
     * @param phone the value for hse_training_plan.phone
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_plan.address
     *
     * @return the value of hse_training_plan.address
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_plan.address
     *
     * @param address the value for hse_training_plan.address
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_plan.number
     *
     * @return the value of hse_training_plan.number
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_plan.number
     *
     * @param number the value for hse_training_plan.number
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public void setNumber(String number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_plan.surplus_number
     *
     * @return the value of hse_training_plan.surplus_number
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public String getSurplusNumber() {
        return surplusNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_plan.surplus_number
     *
     * @param surplusNumber the value for hse_training_plan.surplus_number
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public void setSurplusNumber(String surplusNumber) {
        this.surplusNumber = surplusNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_plan.time
     *
     * @return the value of hse_training_plan.time
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_plan.time
     *
     * @param time the value for hse_training_plan.time
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public void setTime(String time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_plan.attach_id
     *
     * @return the value of hse_training_plan.attach_id
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public String getAttachId() {
        return attachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_plan.attach_id
     *
     * @param attachId the value for hse_training_plan.attach_id
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public void setAttachId(String attachId) {
        this.attachId = attachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_plan.remarks
     *
     * @return the value of hse_training_plan.remarks
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_plan.remarks
     *
     * @param remarks the value for hse_training_plan.remarks
     *
     * @mbggenerated Fri Aug 24 14:50:26 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
}