package com.pcitc.base.engin.hse.training;

import java.io.Serializable;

import com.pcitc.base.util.SearchInfo;

public class TrainingApply extends SearchInfo  implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_apply.data_id
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    private String dataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_apply.create_user
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_apply.create_date
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_apply.update_user
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_apply.update_date
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_apply.status
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_apply.audit_status
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    private String auditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_apply.company_code
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    private String companyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_apply.project_id
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    private String projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_apply.form_code
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    private String formCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_apply.name
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_apply.sex
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_apply.id_card
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_apply.unit_name
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    private String unitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_apply.unit_id
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    private String unitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_apply.apply_person
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    private String applyPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_apply.apply_date
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    private String applyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_apply.remarks
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hse_training_apply.plan_id
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    private String planId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_apply.data_id
     *
     * @return the value of hse_training_apply.data_id
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public String getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_apply.data_id
     *
     * @param dataId the value for hse_training_apply.data_id
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public void setDataId(String dataId) {
        this.dataId = dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_apply.create_user
     *
     * @return the value of hse_training_apply.create_user
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_apply.create_user
     *
     * @param createUser the value for hse_training_apply.create_user
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_apply.create_date
     *
     * @return the value of hse_training_apply.create_date
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_apply.create_date
     *
     * @param createDate the value for hse_training_apply.create_date
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_apply.update_user
     *
     * @return the value of hse_training_apply.update_user
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_apply.update_user
     *
     * @param updateUser the value for hse_training_apply.update_user
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_apply.update_date
     *
     * @return the value of hse_training_apply.update_date
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_apply.update_date
     *
     * @param updateDate the value for hse_training_apply.update_date
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_apply.status
     *
     * @return the value of hse_training_apply.status
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_apply.status
     *
     * @param status the value for hse_training_apply.status
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_apply.audit_status
     *
     * @return the value of hse_training_apply.audit_status
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public String getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_apply.audit_status
     *
     * @param auditStatus the value for hse_training_apply.audit_status
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public void setAuditStatus(String auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_apply.company_code
     *
     * @return the value of hse_training_apply.company_code
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_apply.company_code
     *
     * @param companyCode the value for hse_training_apply.company_code
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_apply.project_id
     *
     * @return the value of hse_training_apply.project_id
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_apply.project_id
     *
     * @param projectId the value for hse_training_apply.project_id
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_apply.form_code
     *
     * @return the value of hse_training_apply.form_code
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public String getFormCode() {
        return formCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_apply.form_code
     *
     * @param formCode the value for hse_training_apply.form_code
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public void setFormCode(String formCode) {
        this.formCode = formCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_apply.name
     *
     * @return the value of hse_training_apply.name
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_apply.name
     *
     * @param name the value for hse_training_apply.name
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_apply.sex
     *
     * @return the value of hse_training_apply.sex
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_apply.sex
     *
     * @param sex the value for hse_training_apply.sex
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_apply.id_card
     *
     * @return the value of hse_training_apply.id_card
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_apply.id_card
     *
     * @param idCard the value for hse_training_apply.id_card
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_apply.unit_name
     *
     * @return the value of hse_training_apply.unit_name
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_apply.unit_name
     *
     * @param unitName the value for hse_training_apply.unit_name
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_apply.unit_id
     *
     * @return the value of hse_training_apply.unit_id
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public String getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_apply.unit_id
     *
     * @param unitId the value for hse_training_apply.unit_id
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public void setUnitId(String unitId) {
        this.unitId = unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_apply.apply_person
     *
     * @return the value of hse_training_apply.apply_person
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public String getApplyPerson() {
        return applyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_apply.apply_person
     *
     * @param applyPerson the value for hse_training_apply.apply_person
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public void setApplyPerson(String applyPerson) {
        this.applyPerson = applyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_apply.apply_date
     *
     * @return the value of hse_training_apply.apply_date
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public String getApplyDate() {
        return applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_apply.apply_date
     *
     * @param applyDate the value for hse_training_apply.apply_date
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public void setApplyDate(String applyDate) {
        this.applyDate = applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_apply.remarks
     *
     * @return the value of hse_training_apply.remarks
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_apply.remarks
     *
     * @param remarks the value for hse_training_apply.remarks
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hse_training_apply.plan_id
     *
     * @return the value of hse_training_apply.plan_id
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public String getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hse_training_apply.plan_id
     *
     * @param planId the value for hse_training_apply.plan_id
     *
     * @mbggenerated Wed Aug 22 15:47:39 CST 2018
     */
    public void setPlanId(String planId) {
        this.planId = planId;
    }
}