package com.pcitc.base.system;

public class SysFunctionGroup {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_function_group.group_id
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	private String groupId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_function_group.group_name
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	private String groupName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_function_group.function_items
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	private String functionItems;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_function_group.create_person_id
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	private String createPersonId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_function_group.create_person_name
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	private String createPersonName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_function_group.create_date
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	private String createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_function_group.remarks
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	private String remarks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_function_group.order_num
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	private Integer orderNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_function_group.status
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	private Integer status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_function_group.group_id
	 * @return  the value of sys_function_group.group_id
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	public String getGroupId() {
		return groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_function_group.group_id
	 * @param groupId  the value for sys_function_group.group_id
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_function_group.group_name
	 * @return  the value of sys_function_group.group_name
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	public String getGroupName() {
		return groupName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_function_group.group_name
	 * @param groupName  the value for sys_function_group.group_name
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_function_group.function_items
	 * @return  the value of sys_function_group.function_items
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	public String getFunctionItems() {
		return functionItems;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_function_group.function_items
	 * @param functionItems  the value for sys_function_group.function_items
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	public void setFunctionItems(String functionItems) {
		this.functionItems = functionItems;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_function_group.create_person_id
	 * @return  the value of sys_function_group.create_person_id
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	public String getCreatePersonId() {
		return createPersonId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_function_group.create_person_id
	 * @param createPersonId  the value for sys_function_group.create_person_id
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	public void setCreatePersonId(String createPersonId) {
		this.createPersonId = createPersonId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_function_group.create_person_name
	 * @return  the value of sys_function_group.create_person_name
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	public String getCreatePersonName() {
		return createPersonName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_function_group.create_person_name
	 * @param createPersonName  the value for sys_function_group.create_person_name
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	public void setCreatePersonName(String createPersonName) {
		this.createPersonName = createPersonName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_function_group.create_date
	 * @return  the value of sys_function_group.create_date
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	public String getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_function_group.create_date
	 * @param createDate  the value for sys_function_group.create_date
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_function_group.remarks
	 * @return  the value of sys_function_group.remarks
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_function_group.remarks
	 * @param remarks  the value for sys_function_group.remarks
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_function_group.order_num
	 * @return  the value of sys_function_group.order_num
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	public Integer getOrderNum() {
		return orderNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_function_group.order_num
	 * @param orderNum  the value for sys_function_group.order_num
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_function_group.status
	 * @return  the value of sys_function_group.status
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_function_group.status
	 * @param status  the value for sys_function_group.status
	 * @mbg.generated  Wed Jun 27 10:06:19 CST 2018
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}
}