package com.pcitc.base.system;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysRoleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_role
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_role
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_role
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public SysRoleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_role
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRoleIdIsNull() {
            addCriterion("role_id is null");
            return (Criteria) this;
        }

        public Criteria andRoleIdIsNotNull() {
            addCriterion("role_id is not null");
            return (Criteria) this;
        }

        public Criteria andRoleIdEqualTo(String value) {
            addCriterion("role_id =", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotEqualTo(String value) {
            addCriterion("role_id <>", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdGreaterThan(String value) {
            addCriterion("role_id >", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdGreaterThanOrEqualTo(String value) {
            addCriterion("role_id >=", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdLessThan(String value) {
            addCriterion("role_id <", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdLessThanOrEqualTo(String value) {
            addCriterion("role_id <=", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdLike(String value) {
            addCriterion("role_id like", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotLike(String value) {
            addCriterion("role_id not like", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdIn(List<String> values) {
            addCriterion("role_id in", values, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotIn(List<String> values) {
            addCriterion("role_id not in", values, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdBetween(String value1, String value2) {
            addCriterion("role_id between", value1, value2, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotBetween(String value1, String value2) {
            addCriterion("role_id not between", value1, value2, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleNameIsNull() {
            addCriterion("role_name is null");
            return (Criteria) this;
        }

        public Criteria andRoleNameIsNotNull() {
            addCriterion("role_name is not null");
            return (Criteria) this;
        }

        public Criteria andRoleNameEqualTo(String value) {
            addCriterion("role_name =", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotEqualTo(String value) {
            addCriterion("role_name <>", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameGreaterThan(String value) {
            addCriterion("role_name >", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameGreaterThanOrEqualTo(String value) {
            addCriterion("role_name >=", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLessThan(String value) {
            addCriterion("role_name <", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLessThanOrEqualTo(String value) {
            addCriterion("role_name <=", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLike(String value) {
            addCriterion("role_name like", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotLike(String value) {
            addCriterion("role_name not like", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameIn(List<String> values) {
            addCriterion("role_name in", values, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotIn(List<String> values) {
            addCriterion("role_name not in", values, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameBetween(String value1, String value2) {
            addCriterion("role_name between", value1, value2, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotBetween(String value1, String value2) {
            addCriterion("role_name not between", value1, value2, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleDataIsNull() {
            addCriterion("role_data is null");
            return (Criteria) this;
        }

        public Criteria andRoleDataIsNotNull() {
            addCriterion("role_data is not null");
            return (Criteria) this;
        }

        public Criteria andRoleDataEqualTo(String value) {
            addCriterion("role_data =", value, "roleData");
            return (Criteria) this;
        }

        public Criteria andRoleDataNotEqualTo(String value) {
            addCriterion("role_data <>", value, "roleData");
            return (Criteria) this;
        }

        public Criteria andRoleDataGreaterThan(String value) {
            addCriterion("role_data >", value, "roleData");
            return (Criteria) this;
        }

        public Criteria andRoleDataGreaterThanOrEqualTo(String value) {
            addCriterion("role_data >=", value, "roleData");
            return (Criteria) this;
        }

        public Criteria andRoleDataLessThan(String value) {
            addCriterion("role_data <", value, "roleData");
            return (Criteria) this;
        }

        public Criteria andRoleDataLessThanOrEqualTo(String value) {
            addCriterion("role_data <=", value, "roleData");
            return (Criteria) this;
        }

        public Criteria andRoleDataLike(String value) {
            addCriterion("role_data like", value, "roleData");
            return (Criteria) this;
        }

        public Criteria andRoleDataNotLike(String value) {
            addCriterion("role_data not like", value, "roleData");
            return (Criteria) this;
        }

        public Criteria andRoleDataIn(List<String> values) {
            addCriterion("role_data in", values, "roleData");
            return (Criteria) this;
        }

        public Criteria andRoleDataNotIn(List<String> values) {
            addCriterion("role_data not in", values, "roleData");
            return (Criteria) this;
        }

        public Criteria andRoleDataBetween(String value1, String value2) {
            addCriterion("role_data between", value1, value2, "roleData");
            return (Criteria) this;
        }

        public Criteria andRoleDataNotBetween(String value1, String value2) {
            addCriterion("role_data not between", value1, value2, "roleData");
            return (Criteria) this;
        }

        public Criteria andRoleFlagIsNull() {
            addCriterion("role_flag is null");
            return (Criteria) this;
        }

        public Criteria andRoleFlagIsNotNull() {
            addCriterion("role_flag is not null");
            return (Criteria) this;
        }

        public Criteria andRoleFlagEqualTo(String value) {
            addCriterion("role_flag =", value, "roleFlag");
            return (Criteria) this;
        }

        public Criteria andRoleFlagNotEqualTo(String value) {
            addCriterion("role_flag <>", value, "roleFlag");
            return (Criteria) this;
        }

        public Criteria andRoleFlagGreaterThan(String value) {
            addCriterion("role_flag >", value, "roleFlag");
            return (Criteria) this;
        }

        public Criteria andRoleFlagGreaterThanOrEqualTo(String value) {
            addCriterion("role_flag >=", value, "roleFlag");
            return (Criteria) this;
        }

        public Criteria andRoleFlagLessThan(String value) {
            addCriterion("role_flag <", value, "roleFlag");
            return (Criteria) this;
        }

        public Criteria andRoleFlagLessThanOrEqualTo(String value) {
            addCriterion("role_flag <=", value, "roleFlag");
            return (Criteria) this;
        }

        public Criteria andRoleFlagLike(String value) {
            addCriterion("role_flag like", value, "roleFlag");
            return (Criteria) this;
        }

        public Criteria andRoleFlagNotLike(String value) {
            addCriterion("role_flag not like", value, "roleFlag");
            return (Criteria) this;
        }

        public Criteria andRoleFlagIn(List<String> values) {
            addCriterion("role_flag in", values, "roleFlag");
            return (Criteria) this;
        }

        public Criteria andRoleFlagNotIn(List<String> values) {
            addCriterion("role_flag not in", values, "roleFlag");
            return (Criteria) this;
        }

        public Criteria andRoleFlagBetween(String value1, String value2) {
            addCriterion("role_flag between", value1, value2, "roleFlag");
            return (Criteria) this;
        }

        public Criteria andRoleFlagNotBetween(String value1, String value2) {
            addCriterion("role_flag not between", value1, value2, "roleFlag");
            return (Criteria) this;
        }

        public Criteria andRoleKindIsNull() {
            addCriterion("role_kind is null");
            return (Criteria) this;
        }

        public Criteria andRoleKindIsNotNull() {
            addCriterion("role_kind is not null");
            return (Criteria) this;
        }

        public Criteria andRoleKindEqualTo(String value) {
            addCriterion("role_kind =", value, "roleKind");
            return (Criteria) this;
        }

        public Criteria andRoleKindNotEqualTo(String value) {
            addCriterion("role_kind <>", value, "roleKind");
            return (Criteria) this;
        }

        public Criteria andRoleKindGreaterThan(String value) {
            addCriterion("role_kind >", value, "roleKind");
            return (Criteria) this;
        }

        public Criteria andRoleKindGreaterThanOrEqualTo(String value) {
            addCriterion("role_kind >=", value, "roleKind");
            return (Criteria) this;
        }

        public Criteria andRoleKindLessThan(String value) {
            addCriterion("role_kind <", value, "roleKind");
            return (Criteria) this;
        }

        public Criteria andRoleKindLessThanOrEqualTo(String value) {
            addCriterion("role_kind <=", value, "roleKind");
            return (Criteria) this;
        }

        public Criteria andRoleKindLike(String value) {
            addCriterion("role_kind like", value, "roleKind");
            return (Criteria) this;
        }

        public Criteria andRoleKindNotLike(String value) {
            addCriterion("role_kind not like", value, "roleKind");
            return (Criteria) this;
        }

        public Criteria andRoleKindIn(List<String> values) {
            addCriterion("role_kind in", values, "roleKind");
            return (Criteria) this;
        }

        public Criteria andRoleKindNotIn(List<String> values) {
            addCriterion("role_kind not in", values, "roleKind");
            return (Criteria) this;
        }

        public Criteria andRoleKindBetween(String value1, String value2) {
            addCriterion("role_kind between", value1, value2, "roleKind");
            return (Criteria) this;
        }

        public Criteria andRoleKindNotBetween(String value1, String value2) {
            addCriterion("role_kind not between", value1, value2, "roleKind");
            return (Criteria) this;
        }

        public Criteria andRoleCreateTimeIsNull() {
            addCriterion("role_create_time is null");
            return (Criteria) this;
        }

        public Criteria andRoleCreateTimeIsNotNull() {
            addCriterion("role_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andRoleCreateTimeEqualTo(Date value) {
            addCriterion("role_create_time =", value, "roleCreateTime");
            return (Criteria) this;
        }

        public Criteria andRoleCreateTimeNotEqualTo(Date value) {
            addCriterion("role_create_time <>", value, "roleCreateTime");
            return (Criteria) this;
        }

        public Criteria andRoleCreateTimeGreaterThan(Date value) {
            addCriterion("role_create_time >", value, "roleCreateTime");
            return (Criteria) this;
        }

        public Criteria andRoleCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("role_create_time >=", value, "roleCreateTime");
            return (Criteria) this;
        }

        public Criteria andRoleCreateTimeLessThan(Date value) {
            addCriterion("role_create_time <", value, "roleCreateTime");
            return (Criteria) this;
        }

        public Criteria andRoleCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("role_create_time <=", value, "roleCreateTime");
            return (Criteria) this;
        }

        public Criteria andRoleCreateTimeIn(List<Date> values) {
            addCriterion("role_create_time in", values, "roleCreateTime");
            return (Criteria) this;
        }

        public Criteria andRoleCreateTimeNotIn(List<Date> values) {
            addCriterion("role_create_time not in", values, "roleCreateTime");
            return (Criteria) this;
        }

        public Criteria andRoleCreateTimeBetween(Date value1, Date value2) {
            addCriterion("role_create_time between", value1, value2, "roleCreateTime");
            return (Criteria) this;
        }

        public Criteria andRoleCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("role_create_time not between", value1, value2, "roleCreateTime");
            return (Criteria) this;
        }

        public Criteria andRoleExtendIsNull() {
            addCriterion("role_extend is null");
            return (Criteria) this;
        }

        public Criteria andRoleExtendIsNotNull() {
            addCriterion("role_extend is not null");
            return (Criteria) this;
        }

        public Criteria andRoleExtendEqualTo(String value) {
            addCriterion("role_extend =", value, "roleExtend");
            return (Criteria) this;
        }

        public Criteria andRoleExtendNotEqualTo(String value) {
            addCriterion("role_extend <>", value, "roleExtend");
            return (Criteria) this;
        }

        public Criteria andRoleExtendGreaterThan(String value) {
            addCriterion("role_extend >", value, "roleExtend");
            return (Criteria) this;
        }

        public Criteria andRoleExtendGreaterThanOrEqualTo(String value) {
            addCriterion("role_extend >=", value, "roleExtend");
            return (Criteria) this;
        }

        public Criteria andRoleExtendLessThan(String value) {
            addCriterion("role_extend <", value, "roleExtend");
            return (Criteria) this;
        }

        public Criteria andRoleExtendLessThanOrEqualTo(String value) {
            addCriterion("role_extend <=", value, "roleExtend");
            return (Criteria) this;
        }

        public Criteria andRoleExtendLike(String value) {
            addCriterion("role_extend like", value, "roleExtend");
            return (Criteria) this;
        }

        public Criteria andRoleExtendNotLike(String value) {
            addCriterion("role_extend not like", value, "roleExtend");
            return (Criteria) this;
        }

        public Criteria andRoleExtendIn(List<String> values) {
            addCriterion("role_extend in", values, "roleExtend");
            return (Criteria) this;
        }

        public Criteria andRoleExtendNotIn(List<String> values) {
            addCriterion("role_extend not in", values, "roleExtend");
            return (Criteria) this;
        }

        public Criteria andRoleExtendBetween(String value1, String value2) {
            addCriterion("role_extend between", value1, value2, "roleExtend");
            return (Criteria) this;
        }

        public Criteria andRoleExtendNotBetween(String value1, String value2) {
            addCriterion("role_extend not between", value1, value2, "roleExtend");
            return (Criteria) this;
        }

        public Criteria andRoleOrderIsNull() {
            addCriterion("role_order is null");
            return (Criteria) this;
        }

        public Criteria andRoleOrderIsNotNull() {
            addCriterion("role_order is not null");
            return (Criteria) this;
        }

        public Criteria andRoleOrderEqualTo(Integer value) {
            addCriterion("role_order =", value, "roleOrder");
            return (Criteria) this;
        }

        public Criteria andRoleOrderNotEqualTo(Integer value) {
            addCriterion("role_order <>", value, "roleOrder");
            return (Criteria) this;
        }

        public Criteria andRoleOrderGreaterThan(Integer value) {
            addCriterion("role_order >", value, "roleOrder");
            return (Criteria) this;
        }

        public Criteria andRoleOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("role_order >=", value, "roleOrder");
            return (Criteria) this;
        }

        public Criteria andRoleOrderLessThan(Integer value) {
            addCriterion("role_order <", value, "roleOrder");
            return (Criteria) this;
        }

        public Criteria andRoleOrderLessThanOrEqualTo(Integer value) {
            addCriterion("role_order <=", value, "roleOrder");
            return (Criteria) this;
        }

        public Criteria andRoleOrderIn(List<Integer> values) {
            addCriterion("role_order in", values, "roleOrder");
            return (Criteria) this;
        }

        public Criteria andRoleOrderNotIn(List<Integer> values) {
            addCriterion("role_order not in", values, "roleOrder");
            return (Criteria) this;
        }

        public Criteria andRoleOrderBetween(Integer value1, Integer value2) {
            addCriterion("role_order between", value1, value2, "roleOrder");
            return (Criteria) this;
        }

        public Criteria andRoleOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("role_order not between", value1, value2, "roleOrder");
            return (Criteria) this;
        }

        public Criteria andRoleCommentIsNull() {
            addCriterion("role_comment is null");
            return (Criteria) this;
        }

        public Criteria andRoleCommentIsNotNull() {
            addCriterion("role_comment is not null");
            return (Criteria) this;
        }

        public Criteria andRoleCommentEqualTo(String value) {
            addCriterion("role_comment =", value, "roleComment");
            return (Criteria) this;
        }

        public Criteria andRoleCommentNotEqualTo(String value) {
            addCriterion("role_comment <>", value, "roleComment");
            return (Criteria) this;
        }

        public Criteria andRoleCommentGreaterThan(String value) {
            addCriterion("role_comment >", value, "roleComment");
            return (Criteria) this;
        }

        public Criteria andRoleCommentGreaterThanOrEqualTo(String value) {
            addCriterion("role_comment >=", value, "roleComment");
            return (Criteria) this;
        }

        public Criteria andRoleCommentLessThan(String value) {
            addCriterion("role_comment <", value, "roleComment");
            return (Criteria) this;
        }

        public Criteria andRoleCommentLessThanOrEqualTo(String value) {
            addCriterion("role_comment <=", value, "roleComment");
            return (Criteria) this;
        }

        public Criteria andRoleCommentLike(String value) {
            addCriterion("role_comment like", value, "roleComment");
            return (Criteria) this;
        }

        public Criteria andRoleCommentNotLike(String value) {
            addCriterion("role_comment not like", value, "roleComment");
            return (Criteria) this;
        }

        public Criteria andRoleCommentIn(List<String> values) {
            addCriterion("role_comment in", values, "roleComment");
            return (Criteria) this;
        }

        public Criteria andRoleCommentNotIn(List<String> values) {
            addCriterion("role_comment not in", values, "roleComment");
            return (Criteria) this;
        }

        public Criteria andRoleCommentBetween(String value1, String value2) {
            addCriterion("role_comment between", value1, value2, "roleComment");
            return (Criteria) this;
        }

        public Criteria andRoleCommentNotBetween(String value1, String value2) {
            addCriterion("role_comment not between", value1, value2, "roleComment");
            return (Criteria) this;
        }

        public Criteria andRoleDelflagIsNull() {
            addCriterion("role_delflag is null");
            return (Criteria) this;
        }

        public Criteria andRoleDelflagIsNotNull() {
            addCriterion("role_delflag is not null");
            return (Criteria) this;
        }

        public Criteria andRoleDelflagEqualTo(Integer value) {
            addCriterion("role_delflag =", value, "roleDelflag");
            return (Criteria) this;
        }

        public Criteria andRoleDelflagNotEqualTo(Integer value) {
            addCriterion("role_delflag <>", value, "roleDelflag");
            return (Criteria) this;
        }

        public Criteria andRoleDelflagGreaterThan(Integer value) {
            addCriterion("role_delflag >", value, "roleDelflag");
            return (Criteria) this;
        }

        public Criteria andRoleDelflagGreaterThanOrEqualTo(Integer value) {
            addCriterion("role_delflag >=", value, "roleDelflag");
            return (Criteria) this;
        }

        public Criteria andRoleDelflagLessThan(Integer value) {
            addCriterion("role_delflag <", value, "roleDelflag");
            return (Criteria) this;
        }

        public Criteria andRoleDelflagLessThanOrEqualTo(Integer value) {
            addCriterion("role_delflag <=", value, "roleDelflag");
            return (Criteria) this;
        }

        public Criteria andRoleDelflagIn(List<Integer> values) {
            addCriterion("role_delflag in", values, "roleDelflag");
            return (Criteria) this;
        }

        public Criteria andRoleDelflagNotIn(List<Integer> values) {
            addCriterion("role_delflag not in", values, "roleDelflag");
            return (Criteria) this;
        }

        public Criteria andRoleDelflagBetween(Integer value1, Integer value2) {
            addCriterion("role_delflag between", value1, value2, "roleDelflag");
            return (Criteria) this;
        }

        public Criteria andRoleDelflagNotBetween(Integer value1, Integer value2) {
            addCriterion("role_delflag not between", value1, value2, "roleDelflag");
            return (Criteria) this;
        }

        public Criteria andRoleLevelIsNull() {
            addCriterion("role_level is null");
            return (Criteria) this;
        }

        public Criteria andRoleLevelIsNotNull() {
            addCriterion("role_level is not null");
            return (Criteria) this;
        }

        public Criteria andRoleLevelEqualTo(Integer value) {
            addCriterion("role_level =", value, "roleLevel");
            return (Criteria) this;
        }

        public Criteria andRoleLevelNotEqualTo(Integer value) {
            addCriterion("role_level <>", value, "roleLevel");
            return (Criteria) this;
        }

        public Criteria andRoleLevelGreaterThan(Integer value) {
            addCriterion("role_level >", value, "roleLevel");
            return (Criteria) this;
        }

        public Criteria andRoleLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("role_level >=", value, "roleLevel");
            return (Criteria) this;
        }

        public Criteria andRoleLevelLessThan(Integer value) {
            addCriterion("role_level <", value, "roleLevel");
            return (Criteria) this;
        }

        public Criteria andRoleLevelLessThanOrEqualTo(Integer value) {
            addCriterion("role_level <=", value, "roleLevel");
            return (Criteria) this;
        }

        public Criteria andRoleLevelIn(List<Integer> values) {
            addCriterion("role_level in", values, "roleLevel");
            return (Criteria) this;
        }

        public Criteria andRoleLevelNotIn(List<Integer> values) {
            addCriterion("role_level not in", values, "roleLevel");
            return (Criteria) this;
        }

        public Criteria andRoleLevelBetween(Integer value1, Integer value2) {
            addCriterion("role_level between", value1, value2, "roleLevel");
            return (Criteria) this;
        }

        public Criteria andRoleLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("role_level not between", value1, value2, "roleLevel");
            return (Criteria) this;
        }

        public Criteria andRoleRelationIsNull() {
            addCriterion("role_relation is null");
            return (Criteria) this;
        }

        public Criteria andRoleRelationIsNotNull() {
            addCriterion("role_relation is not null");
            return (Criteria) this;
        }

        public Criteria andRoleRelationEqualTo(String value) {
            addCriterion("role_relation =", value, "roleRelation");
            return (Criteria) this;
        }

        public Criteria andRoleRelationNotEqualTo(String value) {
            addCriterion("role_relation <>", value, "roleRelation");
            return (Criteria) this;
        }

        public Criteria andRoleRelationGreaterThan(String value) {
            addCriterion("role_relation >", value, "roleRelation");
            return (Criteria) this;
        }

        public Criteria andRoleRelationGreaterThanOrEqualTo(String value) {
            addCriterion("role_relation >=", value, "roleRelation");
            return (Criteria) this;
        }

        public Criteria andRoleRelationLessThan(String value) {
            addCriterion("role_relation <", value, "roleRelation");
            return (Criteria) this;
        }

        public Criteria andRoleRelationLessThanOrEqualTo(String value) {
            addCriterion("role_relation <=", value, "roleRelation");
            return (Criteria) this;
        }

        public Criteria andRoleRelationLike(String value) {
            addCriterion("role_relation like", value, "roleRelation");
            return (Criteria) this;
        }

        public Criteria andRoleRelationNotLike(String value) {
            addCriterion("role_relation not like", value, "roleRelation");
            return (Criteria) this;
        }

        public Criteria andRoleRelationIn(List<String> values) {
            addCriterion("role_relation in", values, "roleRelation");
            return (Criteria) this;
        }

        public Criteria andRoleRelationNotIn(List<String> values) {
            addCriterion("role_relation not in", values, "roleRelation");
            return (Criteria) this;
        }

        public Criteria andRoleRelationBetween(String value1, String value2) {
            addCriterion("role_relation between", value1, value2, "roleRelation");
            return (Criteria) this;
        }

        public Criteria andRoleRelationNotBetween(String value1, String value2) {
            addCriterion("role_relation not between", value1, value2, "roleRelation");
            return (Criteria) this;
        }

        public Criteria andRoleFuncpopeIsNull() {
            addCriterion("role_funcpope is null");
            return (Criteria) this;
        }

        public Criteria andRoleFuncpopeIsNotNull() {
            addCriterion("role_funcpope is not null");
            return (Criteria) this;
        }

        public Criteria andRoleFuncpopeEqualTo(String value) {
            addCriterion("role_funcpope =", value, "roleFuncpope");
            return (Criteria) this;
        }

        public Criteria andRoleFuncpopeNotEqualTo(String value) {
            addCriterion("role_funcpope <>", value, "roleFuncpope");
            return (Criteria) this;
        }

        public Criteria andRoleFuncpopeGreaterThan(String value) {
            addCriterion("role_funcpope >", value, "roleFuncpope");
            return (Criteria) this;
        }

        public Criteria andRoleFuncpopeGreaterThanOrEqualTo(String value) {
            addCriterion("role_funcpope >=", value, "roleFuncpope");
            return (Criteria) this;
        }

        public Criteria andRoleFuncpopeLessThan(String value) {
            addCriterion("role_funcpope <", value, "roleFuncpope");
            return (Criteria) this;
        }

        public Criteria andRoleFuncpopeLessThanOrEqualTo(String value) {
            addCriterion("role_funcpope <=", value, "roleFuncpope");
            return (Criteria) this;
        }

        public Criteria andRoleFuncpopeLike(String value) {
            addCriterion("role_funcpope like", value, "roleFuncpope");
            return (Criteria) this;
        }

        public Criteria andRoleFuncpopeNotLike(String value) {
            addCriterion("role_funcpope not like", value, "roleFuncpope");
            return (Criteria) this;
        }

        public Criteria andRoleFuncpopeIn(List<String> values) {
            addCriterion("role_funcpope in", values, "roleFuncpope");
            return (Criteria) this;
        }

        public Criteria andRoleFuncpopeNotIn(List<String> values) {
            addCriterion("role_funcpope not in", values, "roleFuncpope");
            return (Criteria) this;
        }

        public Criteria andRoleFuncpopeBetween(String value1, String value2) {
            addCriterion("role_funcpope between", value1, value2, "roleFuncpope");
            return (Criteria) this;
        }

        public Criteria andRoleFuncpopeNotBetween(String value1, String value2) {
            addCriterion("role_funcpope not between", value1, value2, "roleFuncpope");
            return (Criteria) this;
        }

        public Criteria andRoleButnpopeIsNull() {
            addCriterion("role_butnpope is null");
            return (Criteria) this;
        }

        public Criteria andRoleButnpopeIsNotNull() {
            addCriterion("role_butnpope is not null");
            return (Criteria) this;
        }

        public Criteria andRoleButnpopeEqualTo(String value) {
            addCriterion("role_butnpope =", value, "roleButnpope");
            return (Criteria) this;
        }

        public Criteria andRoleButnpopeNotEqualTo(String value) {
            addCriterion("role_butnpope <>", value, "roleButnpope");
            return (Criteria) this;
        }

        public Criteria andRoleButnpopeGreaterThan(String value) {
            addCriterion("role_butnpope >", value, "roleButnpope");
            return (Criteria) this;
        }

        public Criteria andRoleButnpopeGreaterThanOrEqualTo(String value) {
            addCriterion("role_butnpope >=", value, "roleButnpope");
            return (Criteria) this;
        }

        public Criteria andRoleButnpopeLessThan(String value) {
            addCriterion("role_butnpope <", value, "roleButnpope");
            return (Criteria) this;
        }

        public Criteria andRoleButnpopeLessThanOrEqualTo(String value) {
            addCriterion("role_butnpope <=", value, "roleButnpope");
            return (Criteria) this;
        }

        public Criteria andRoleButnpopeLike(String value) {
            addCriterion("role_butnpope like", value, "roleButnpope");
            return (Criteria) this;
        }

        public Criteria andRoleButnpopeNotLike(String value) {
            addCriterion("role_butnpope not like", value, "roleButnpope");
            return (Criteria) this;
        }

        public Criteria andRoleButnpopeIn(List<String> values) {
            addCriterion("role_butnpope in", values, "roleButnpope");
            return (Criteria) this;
        }

        public Criteria andRoleButnpopeNotIn(List<String> values) {
            addCriterion("role_butnpope not in", values, "roleButnpope");
            return (Criteria) this;
        }

        public Criteria andRoleButnpopeBetween(String value1, String value2) {
            addCriterion("role_butnpope between", value1, value2, "roleButnpope");
            return (Criteria) this;
        }

        public Criteria andRoleButnpopeNotBetween(String value1, String value2) {
            addCriterion("role_butnpope not between", value1, value2, "roleButnpope");
            return (Criteria) this;
        }

        public Criteria andRoleDatapopeIsNull() {
            addCriterion("role_datapope is null");
            return (Criteria) this;
        }

        public Criteria andRoleDatapopeIsNotNull() {
            addCriterion("role_datapope is not null");
            return (Criteria) this;
        }

        public Criteria andRoleDatapopeEqualTo(String value) {
            addCriterion("role_datapope =", value, "roleDatapope");
            return (Criteria) this;
        }

        public Criteria andRoleDatapopeNotEqualTo(String value) {
            addCriterion("role_datapope <>", value, "roleDatapope");
            return (Criteria) this;
        }

        public Criteria andRoleDatapopeGreaterThan(String value) {
            addCriterion("role_datapope >", value, "roleDatapope");
            return (Criteria) this;
        }

        public Criteria andRoleDatapopeGreaterThanOrEqualTo(String value) {
            addCriterion("role_datapope >=", value, "roleDatapope");
            return (Criteria) this;
        }

        public Criteria andRoleDatapopeLessThan(String value) {
            addCriterion("role_datapope <", value, "roleDatapope");
            return (Criteria) this;
        }

        public Criteria andRoleDatapopeLessThanOrEqualTo(String value) {
            addCriterion("role_datapope <=", value, "roleDatapope");
            return (Criteria) this;
        }

        public Criteria andRoleDatapopeLike(String value) {
            addCriterion("role_datapope like", value, "roleDatapope");
            return (Criteria) this;
        }

        public Criteria andRoleDatapopeNotLike(String value) {
            addCriterion("role_datapope not like", value, "roleDatapope");
            return (Criteria) this;
        }

        public Criteria andRoleDatapopeIn(List<String> values) {
            addCriterion("role_datapope in", values, "roleDatapope");
            return (Criteria) this;
        }

        public Criteria andRoleDatapopeNotIn(List<String> values) {
            addCriterion("role_datapope not in", values, "roleDatapope");
            return (Criteria) this;
        }

        public Criteria andRoleDatapopeBetween(String value1, String value2) {
            addCriterion("role_datapope between", value1, value2, "roleDatapope");
            return (Criteria) this;
        }

        public Criteria andRoleDatapopeNotBetween(String value1, String value2) {
            addCriterion("role_datapope not between", value1, value2, "roleDatapope");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_role
     *
     * @mbg.generated do_not_delete_during_merge Fri Apr 13 16:40:44 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_role
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}