package com.pcitc.base.system;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysUnitExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_unit
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_unit
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_unit
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_unit
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public SysUnitExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_unit
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_unit
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_unit
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_unit
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_unit
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_unit
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_unit
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_unit
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_unit
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_unit
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_unit
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUnitIdIsNull() {
            addCriterion("unit_id is null");
            return (Criteria) this;
        }

        public Criteria andUnitIdIsNotNull() {
            addCriterion("unit_id is not null");
            return (Criteria) this;
        }

        public Criteria andUnitIdEqualTo(String value) {
            addCriterion("unit_id =", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdNotEqualTo(String value) {
            addCriterion("unit_id <>", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdGreaterThan(String value) {
            addCriterion("unit_id >", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdGreaterThanOrEqualTo(String value) {
            addCriterion("unit_id >=", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdLessThan(String value) {
            addCriterion("unit_id <", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdLessThanOrEqualTo(String value) {
            addCriterion("unit_id <=", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdLike(String value) {
            addCriterion("unit_id like", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdNotLike(String value) {
            addCriterion("unit_id not like", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdIn(List<String> values) {
            addCriterion("unit_id in", values, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdNotIn(List<String> values) {
            addCriterion("unit_id not in", values, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdBetween(String value1, String value2) {
            addCriterion("unit_id between", value1, value2, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdNotBetween(String value1, String value2) {
            addCriterion("unit_id not between", value1, value2, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitNameIsNull() {
            addCriterion("unit_name is null");
            return (Criteria) this;
        }

        public Criteria andUnitNameIsNotNull() {
            addCriterion("unit_name is not null");
            return (Criteria) this;
        }

        public Criteria andUnitNameEqualTo(String value) {
            addCriterion("unit_name =", value, "unitName");
            return (Criteria) this;
        }

        public Criteria andUnitNameNotEqualTo(String value) {
            addCriterion("unit_name <>", value, "unitName");
            return (Criteria) this;
        }

        public Criteria andUnitNameGreaterThan(String value) {
            addCriterion("unit_name >", value, "unitName");
            return (Criteria) this;
        }

        public Criteria andUnitNameGreaterThanOrEqualTo(String value) {
            addCriterion("unit_name >=", value, "unitName");
            return (Criteria) this;
        }

        public Criteria andUnitNameLessThan(String value) {
            addCriterion("unit_name <", value, "unitName");
            return (Criteria) this;
        }

        public Criteria andUnitNameLessThanOrEqualTo(String value) {
            addCriterion("unit_name <=", value, "unitName");
            return (Criteria) this;
        }

        public Criteria andUnitNameLike(String value) {
            addCriterion("unit_name like", value, "unitName");
            return (Criteria) this;
        }

        public Criteria andUnitNameNotLike(String value) {
            addCriterion("unit_name not like", value, "unitName");
            return (Criteria) this;
        }

        public Criteria andUnitNameIn(List<String> values) {
            addCriterion("unit_name in", values, "unitName");
            return (Criteria) this;
        }

        public Criteria andUnitNameNotIn(List<String> values) {
            addCriterion("unit_name not in", values, "unitName");
            return (Criteria) this;
        }

        public Criteria andUnitNameBetween(String value1, String value2) {
            addCriterion("unit_name between", value1, value2, "unitName");
            return (Criteria) this;
        }

        public Criteria andUnitNameNotBetween(String value1, String value2) {
            addCriterion("unit_name not between", value1, value2, "unitName");
            return (Criteria) this;
        }

        public Criteria andUnitAbbrIsNull() {
            addCriterion("unit_abbr is null");
            return (Criteria) this;
        }

        public Criteria andUnitAbbrIsNotNull() {
            addCriterion("unit_abbr is not null");
            return (Criteria) this;
        }

        public Criteria andUnitAbbrEqualTo(String value) {
            addCriterion("unit_abbr =", value, "unitAbbr");
            return (Criteria) this;
        }

        public Criteria andUnitAbbrNotEqualTo(String value) {
            addCriterion("unit_abbr <>", value, "unitAbbr");
            return (Criteria) this;
        }

        public Criteria andUnitAbbrGreaterThan(String value) {
            addCriterion("unit_abbr >", value, "unitAbbr");
            return (Criteria) this;
        }

        public Criteria andUnitAbbrGreaterThanOrEqualTo(String value) {
            addCriterion("unit_abbr >=", value, "unitAbbr");
            return (Criteria) this;
        }

        public Criteria andUnitAbbrLessThan(String value) {
            addCriterion("unit_abbr <", value, "unitAbbr");
            return (Criteria) this;
        }

        public Criteria andUnitAbbrLessThanOrEqualTo(String value) {
            addCriterion("unit_abbr <=", value, "unitAbbr");
            return (Criteria) this;
        }

        public Criteria andUnitAbbrLike(String value) {
            addCriterion("unit_abbr like", value, "unitAbbr");
            return (Criteria) this;
        }

        public Criteria andUnitAbbrNotLike(String value) {
            addCriterion("unit_abbr not like", value, "unitAbbr");
            return (Criteria) this;
        }

        public Criteria andUnitAbbrIn(List<String> values) {
            addCriterion("unit_abbr in", values, "unitAbbr");
            return (Criteria) this;
        }

        public Criteria andUnitAbbrNotIn(List<String> values) {
            addCriterion("unit_abbr not in", values, "unitAbbr");
            return (Criteria) this;
        }

        public Criteria andUnitAbbrBetween(String value1, String value2) {
            addCriterion("unit_abbr between", value1, value2, "unitAbbr");
            return (Criteria) this;
        }

        public Criteria andUnitAbbrNotBetween(String value1, String value2) {
            addCriterion("unit_abbr not between", value1, value2, "unitAbbr");
            return (Criteria) this;
        }

        public Criteria andUnitCodeIsNull() {
            addCriterion("unit_code is null");
            return (Criteria) this;
        }

        public Criteria andUnitCodeIsNotNull() {
            addCriterion("unit_code is not null");
            return (Criteria) this;
        }

        public Criteria andUnitCodeEqualTo(String value) {
            addCriterion("unit_code =", value, "unitCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeNotEqualTo(String value) {
            addCriterion("unit_code <>", value, "unitCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeGreaterThan(String value) {
            addCriterion("unit_code >", value, "unitCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeGreaterThanOrEqualTo(String value) {
            addCriterion("unit_code >=", value, "unitCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeLessThan(String value) {
            addCriterion("unit_code <", value, "unitCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeLessThanOrEqualTo(String value) {
            addCriterion("unit_code <=", value, "unitCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeLike(String value) {
            addCriterion("unit_code like", value, "unitCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeNotLike(String value) {
            addCriterion("unit_code not like", value, "unitCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeIn(List<String> values) {
            addCriterion("unit_code in", values, "unitCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeNotIn(List<String> values) {
            addCriterion("unit_code not in", values, "unitCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeBetween(String value1, String value2) {
            addCriterion("unit_code between", value1, value2, "unitCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeNotBetween(String value1, String value2) {
            addCriterion("unit_code not between", value1, value2, "unitCode");
            return (Criteria) this;
        }

        public Criteria andUnitFlagIsNull() {
            addCriterion("unit_flag is null");
            return (Criteria) this;
        }

        public Criteria andUnitFlagIsNotNull() {
            addCriterion("unit_flag is not null");
            return (Criteria) this;
        }

        public Criteria andUnitFlagEqualTo(String value) {
            addCriterion("unit_flag =", value, "unitFlag");
            return (Criteria) this;
        }

        public Criteria andUnitFlagNotEqualTo(String value) {
            addCriterion("unit_flag <>", value, "unitFlag");
            return (Criteria) this;
        }

        public Criteria andUnitFlagGreaterThan(String value) {
            addCriterion("unit_flag >", value, "unitFlag");
            return (Criteria) this;
        }

        public Criteria andUnitFlagGreaterThanOrEqualTo(String value) {
            addCriterion("unit_flag >=", value, "unitFlag");
            return (Criteria) this;
        }

        public Criteria andUnitFlagLessThan(String value) {
            addCriterion("unit_flag <", value, "unitFlag");
            return (Criteria) this;
        }

        public Criteria andUnitFlagLessThanOrEqualTo(String value) {
            addCriterion("unit_flag <=", value, "unitFlag");
            return (Criteria) this;
        }

        public Criteria andUnitFlagLike(String value) {
            addCriterion("unit_flag like", value, "unitFlag");
            return (Criteria) this;
        }

        public Criteria andUnitFlagNotLike(String value) {
            addCriterion("unit_flag not like", value, "unitFlag");
            return (Criteria) this;
        }

        public Criteria andUnitFlagIn(List<String> values) {
            addCriterion("unit_flag in", values, "unitFlag");
            return (Criteria) this;
        }

        public Criteria andUnitFlagNotIn(List<String> values) {
            addCriterion("unit_flag not in", values, "unitFlag");
            return (Criteria) this;
        }

        public Criteria andUnitFlagBetween(String value1, String value2) {
            addCriterion("unit_flag between", value1, value2, "unitFlag");
            return (Criteria) this;
        }

        public Criteria andUnitFlagNotBetween(String value1, String value2) {
            addCriterion("unit_flag not between", value1, value2, "unitFlag");
            return (Criteria) this;
        }

        public Criteria andUnitKindIsNull() {
            addCriterion("unit_kind is null");
            return (Criteria) this;
        }

        public Criteria andUnitKindIsNotNull() {
            addCriterion("unit_kind is not null");
            return (Criteria) this;
        }

        public Criteria andUnitKindEqualTo(String value) {
            addCriterion("unit_kind =", value, "unitKind");
            return (Criteria) this;
        }

        public Criteria andUnitKindNotEqualTo(String value) {
            addCriterion("unit_kind <>", value, "unitKind");
            return (Criteria) this;
        }

        public Criteria andUnitKindGreaterThan(String value) {
            addCriterion("unit_kind >", value, "unitKind");
            return (Criteria) this;
        }

        public Criteria andUnitKindGreaterThanOrEqualTo(String value) {
            addCriterion("unit_kind >=", value, "unitKind");
            return (Criteria) this;
        }

        public Criteria andUnitKindLessThan(String value) {
            addCriterion("unit_kind <", value, "unitKind");
            return (Criteria) this;
        }

        public Criteria andUnitKindLessThanOrEqualTo(String value) {
            addCriterion("unit_kind <=", value, "unitKind");
            return (Criteria) this;
        }

        public Criteria andUnitKindLike(String value) {
            addCriterion("unit_kind like", value, "unitKind");
            return (Criteria) this;
        }

        public Criteria andUnitKindNotLike(String value) {
            addCriterion("unit_kind not like", value, "unitKind");
            return (Criteria) this;
        }

        public Criteria andUnitKindIn(List<String> values) {
            addCriterion("unit_kind in", values, "unitKind");
            return (Criteria) this;
        }

        public Criteria andUnitKindNotIn(List<String> values) {
            addCriterion("unit_kind not in", values, "unitKind");
            return (Criteria) this;
        }

        public Criteria andUnitKindBetween(String value1, String value2) {
            addCriterion("unit_kind between", value1, value2, "unitKind");
            return (Criteria) this;
        }

        public Criteria andUnitKindNotBetween(String value1, String value2) {
            addCriterion("unit_kind not between", value1, value2, "unitKind");
            return (Criteria) this;
        }

        public Criteria andUnitCreateTimeIsNull() {
            addCriterion("unit_create_time is null");
            return (Criteria) this;
        }

        public Criteria andUnitCreateTimeIsNotNull() {
            addCriterion("unit_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andUnitCreateTimeEqualTo(Date value) {
            addCriterion("unit_create_time =", value, "unitCreateTime");
            return (Criteria) this;
        }

        public Criteria andUnitCreateTimeNotEqualTo(Date value) {
            addCriterion("unit_create_time <>", value, "unitCreateTime");
            return (Criteria) this;
        }

        public Criteria andUnitCreateTimeGreaterThan(Date value) {
            addCriterion("unit_create_time >", value, "unitCreateTime");
            return (Criteria) this;
        }

        public Criteria andUnitCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("unit_create_time >=", value, "unitCreateTime");
            return (Criteria) this;
        }

        public Criteria andUnitCreateTimeLessThan(Date value) {
            addCriterion("unit_create_time <", value, "unitCreateTime");
            return (Criteria) this;
        }

        public Criteria andUnitCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("unit_create_time <=", value, "unitCreateTime");
            return (Criteria) this;
        }

        public Criteria andUnitCreateTimeIn(List<Date> values) {
            addCriterion("unit_create_time in", values, "unitCreateTime");
            return (Criteria) this;
        }

        public Criteria andUnitCreateTimeNotIn(List<Date> values) {
            addCriterion("unit_create_time not in", values, "unitCreateTime");
            return (Criteria) this;
        }

        public Criteria andUnitCreateTimeBetween(Date value1, Date value2) {
            addCriterion("unit_create_time between", value1, value2, "unitCreateTime");
            return (Criteria) this;
        }

        public Criteria andUnitCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("unit_create_time not between", value1, value2, "unitCreateTime");
            return (Criteria) this;
        }

        public Criteria andUnitExtendIsNull() {
            addCriterion("unit_extend is null");
            return (Criteria) this;
        }

        public Criteria andUnitExtendIsNotNull() {
            addCriterion("unit_extend is not null");
            return (Criteria) this;
        }

        public Criteria andUnitExtendEqualTo(String value) {
            addCriterion("unit_extend =", value, "unitExtend");
            return (Criteria) this;
        }

        public Criteria andUnitExtendNotEqualTo(String value) {
            addCriterion("unit_extend <>", value, "unitExtend");
            return (Criteria) this;
        }

        public Criteria andUnitExtendGreaterThan(String value) {
            addCriterion("unit_extend >", value, "unitExtend");
            return (Criteria) this;
        }

        public Criteria andUnitExtendGreaterThanOrEqualTo(String value) {
            addCriterion("unit_extend >=", value, "unitExtend");
            return (Criteria) this;
        }

        public Criteria andUnitExtendLessThan(String value) {
            addCriterion("unit_extend <", value, "unitExtend");
            return (Criteria) this;
        }

        public Criteria andUnitExtendLessThanOrEqualTo(String value) {
            addCriterion("unit_extend <=", value, "unitExtend");
            return (Criteria) this;
        }

        public Criteria andUnitExtendLike(String value) {
            addCriterion("unit_extend like", value, "unitExtend");
            return (Criteria) this;
        }

        public Criteria andUnitExtendNotLike(String value) {
            addCriterion("unit_extend not like", value, "unitExtend");
            return (Criteria) this;
        }

        public Criteria andUnitExtendIn(List<String> values) {
            addCriterion("unit_extend in", values, "unitExtend");
            return (Criteria) this;
        }

        public Criteria andUnitExtendNotIn(List<String> values) {
            addCriterion("unit_extend not in", values, "unitExtend");
            return (Criteria) this;
        }

        public Criteria andUnitExtendBetween(String value1, String value2) {
            addCriterion("unit_extend between", value1, value2, "unitExtend");
            return (Criteria) this;
        }

        public Criteria andUnitExtendNotBetween(String value1, String value2) {
            addCriterion("unit_extend not between", value1, value2, "unitExtend");
            return (Criteria) this;
        }

        public Criteria andUnitOrderIsNull() {
            addCriterion("unit_order is null");
            return (Criteria) this;
        }

        public Criteria andUnitOrderIsNotNull() {
            addCriterion("unit_order is not null");
            return (Criteria) this;
        }

        public Criteria andUnitOrderEqualTo(Integer value) {
            addCriterion("unit_order =", value, "unitOrder");
            return (Criteria) this;
        }

        public Criteria andUnitOrderNotEqualTo(Integer value) {
            addCriterion("unit_order <>", value, "unitOrder");
            return (Criteria) this;
        }

        public Criteria andUnitOrderGreaterThan(Integer value) {
            addCriterion("unit_order >", value, "unitOrder");
            return (Criteria) this;
        }

        public Criteria andUnitOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("unit_order >=", value, "unitOrder");
            return (Criteria) this;
        }

        public Criteria andUnitOrderLessThan(Integer value) {
            addCriterion("unit_order <", value, "unitOrder");
            return (Criteria) this;
        }

        public Criteria andUnitOrderLessThanOrEqualTo(Integer value) {
            addCriterion("unit_order <=", value, "unitOrder");
            return (Criteria) this;
        }

        public Criteria andUnitOrderIn(List<Integer> values) {
            addCriterion("unit_order in", values, "unitOrder");
            return (Criteria) this;
        }

        public Criteria andUnitOrderNotIn(List<Integer> values) {
            addCriterion("unit_order not in", values, "unitOrder");
            return (Criteria) this;
        }

        public Criteria andUnitOrderBetween(Integer value1, Integer value2) {
            addCriterion("unit_order between", value1, value2, "unitOrder");
            return (Criteria) this;
        }

        public Criteria andUnitOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("unit_order not between", value1, value2, "unitOrder");
            return (Criteria) this;
        }

        public Criteria andUnitCommentIsNull() {
            addCriterion("unit_comment is null");
            return (Criteria) this;
        }

        public Criteria andUnitCommentIsNotNull() {
            addCriterion("unit_comment is not null");
            return (Criteria) this;
        }

        public Criteria andUnitCommentEqualTo(String value) {
            addCriterion("unit_comment =", value, "unitComment");
            return (Criteria) this;
        }

        public Criteria andUnitCommentNotEqualTo(String value) {
            addCriterion("unit_comment <>", value, "unitComment");
            return (Criteria) this;
        }

        public Criteria andUnitCommentGreaterThan(String value) {
            addCriterion("unit_comment >", value, "unitComment");
            return (Criteria) this;
        }

        public Criteria andUnitCommentGreaterThanOrEqualTo(String value) {
            addCriterion("unit_comment >=", value, "unitComment");
            return (Criteria) this;
        }

        public Criteria andUnitCommentLessThan(String value) {
            addCriterion("unit_comment <", value, "unitComment");
            return (Criteria) this;
        }

        public Criteria andUnitCommentLessThanOrEqualTo(String value) {
            addCriterion("unit_comment <=", value, "unitComment");
            return (Criteria) this;
        }

        public Criteria andUnitCommentLike(String value) {
            addCriterion("unit_comment like", value, "unitComment");
            return (Criteria) this;
        }

        public Criteria andUnitCommentNotLike(String value) {
            addCriterion("unit_comment not like", value, "unitComment");
            return (Criteria) this;
        }

        public Criteria andUnitCommentIn(List<String> values) {
            addCriterion("unit_comment in", values, "unitComment");
            return (Criteria) this;
        }

        public Criteria andUnitCommentNotIn(List<String> values) {
            addCriterion("unit_comment not in", values, "unitComment");
            return (Criteria) this;
        }

        public Criteria andUnitCommentBetween(String value1, String value2) {
            addCriterion("unit_comment between", value1, value2, "unitComment");
            return (Criteria) this;
        }

        public Criteria andUnitCommentNotBetween(String value1, String value2) {
            addCriterion("unit_comment not between", value1, value2, "unitComment");
            return (Criteria) this;
        }

        public Criteria andUnitPhoneIsNull() {
            addCriterion("unit_phone is null");
            return (Criteria) this;
        }

        public Criteria andUnitPhoneIsNotNull() {
            addCriterion("unit_phone is not null");
            return (Criteria) this;
        }

        public Criteria andUnitPhoneEqualTo(String value) {
            addCriterion("unit_phone =", value, "unitPhone");
            return (Criteria) this;
        }

        public Criteria andUnitPhoneNotEqualTo(String value) {
            addCriterion("unit_phone <>", value, "unitPhone");
            return (Criteria) this;
        }

        public Criteria andUnitPhoneGreaterThan(String value) {
            addCriterion("unit_phone >", value, "unitPhone");
            return (Criteria) this;
        }

        public Criteria andUnitPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("unit_phone >=", value, "unitPhone");
            return (Criteria) this;
        }

        public Criteria andUnitPhoneLessThan(String value) {
            addCriterion("unit_phone <", value, "unitPhone");
            return (Criteria) this;
        }

        public Criteria andUnitPhoneLessThanOrEqualTo(String value) {
            addCriterion("unit_phone <=", value, "unitPhone");
            return (Criteria) this;
        }

        public Criteria andUnitPhoneLike(String value) {
            addCriterion("unit_phone like", value, "unitPhone");
            return (Criteria) this;
        }

        public Criteria andUnitPhoneNotLike(String value) {
            addCriterion("unit_phone not like", value, "unitPhone");
            return (Criteria) this;
        }

        public Criteria andUnitPhoneIn(List<String> values) {
            addCriterion("unit_phone in", values, "unitPhone");
            return (Criteria) this;
        }

        public Criteria andUnitPhoneNotIn(List<String> values) {
            addCriterion("unit_phone not in", values, "unitPhone");
            return (Criteria) this;
        }

        public Criteria andUnitPhoneBetween(String value1, String value2) {
            addCriterion("unit_phone between", value1, value2, "unitPhone");
            return (Criteria) this;
        }

        public Criteria andUnitPhoneNotBetween(String value1, String value2) {
            addCriterion("unit_phone not between", value1, value2, "unitPhone");
            return (Criteria) this;
        }

        public Criteria andUnitFaxIsNull() {
            addCriterion("unit_fax is null");
            return (Criteria) this;
        }

        public Criteria andUnitFaxIsNotNull() {
            addCriterion("unit_fax is not null");
            return (Criteria) this;
        }

        public Criteria andUnitFaxEqualTo(String value) {
            addCriterion("unit_fax =", value, "unitFax");
            return (Criteria) this;
        }

        public Criteria andUnitFaxNotEqualTo(String value) {
            addCriterion("unit_fax <>", value, "unitFax");
            return (Criteria) this;
        }

        public Criteria andUnitFaxGreaterThan(String value) {
            addCriterion("unit_fax >", value, "unitFax");
            return (Criteria) this;
        }

        public Criteria andUnitFaxGreaterThanOrEqualTo(String value) {
            addCriterion("unit_fax >=", value, "unitFax");
            return (Criteria) this;
        }

        public Criteria andUnitFaxLessThan(String value) {
            addCriterion("unit_fax <", value, "unitFax");
            return (Criteria) this;
        }

        public Criteria andUnitFaxLessThanOrEqualTo(String value) {
            addCriterion("unit_fax <=", value, "unitFax");
            return (Criteria) this;
        }

        public Criteria andUnitFaxLike(String value) {
            addCriterion("unit_fax like", value, "unitFax");
            return (Criteria) this;
        }

        public Criteria andUnitFaxNotLike(String value) {
            addCriterion("unit_fax not like", value, "unitFax");
            return (Criteria) this;
        }

        public Criteria andUnitFaxIn(List<String> values) {
            addCriterion("unit_fax in", values, "unitFax");
            return (Criteria) this;
        }

        public Criteria andUnitFaxNotIn(List<String> values) {
            addCriterion("unit_fax not in", values, "unitFax");
            return (Criteria) this;
        }

        public Criteria andUnitFaxBetween(String value1, String value2) {
            addCriterion("unit_fax between", value1, value2, "unitFax");
            return (Criteria) this;
        }

        public Criteria andUnitFaxNotBetween(String value1, String value2) {
            addCriterion("unit_fax not between", value1, value2, "unitFax");
            return (Criteria) this;
        }

        public Criteria andUnitManagerIsNull() {
            addCriterion("unit_manager is null");
            return (Criteria) this;
        }

        public Criteria andUnitManagerIsNotNull() {
            addCriterion("unit_manager is not null");
            return (Criteria) this;
        }

        public Criteria andUnitManagerEqualTo(String value) {
            addCriterion("unit_manager =", value, "unitManager");
            return (Criteria) this;
        }

        public Criteria andUnitManagerNotEqualTo(String value) {
            addCriterion("unit_manager <>", value, "unitManager");
            return (Criteria) this;
        }

        public Criteria andUnitManagerGreaterThan(String value) {
            addCriterion("unit_manager >", value, "unitManager");
            return (Criteria) this;
        }

        public Criteria andUnitManagerGreaterThanOrEqualTo(String value) {
            addCriterion("unit_manager >=", value, "unitManager");
            return (Criteria) this;
        }

        public Criteria andUnitManagerLessThan(String value) {
            addCriterion("unit_manager <", value, "unitManager");
            return (Criteria) this;
        }

        public Criteria andUnitManagerLessThanOrEqualTo(String value) {
            addCriterion("unit_manager <=", value, "unitManager");
            return (Criteria) this;
        }

        public Criteria andUnitManagerLike(String value) {
            addCriterion("unit_manager like", value, "unitManager");
            return (Criteria) this;
        }

        public Criteria andUnitManagerNotLike(String value) {
            addCriterion("unit_manager not like", value, "unitManager");
            return (Criteria) this;
        }

        public Criteria andUnitManagerIn(List<String> values) {
            addCriterion("unit_manager in", values, "unitManager");
            return (Criteria) this;
        }

        public Criteria andUnitManagerNotIn(List<String> values) {
            addCriterion("unit_manager not in", values, "unitManager");
            return (Criteria) this;
        }

        public Criteria andUnitManagerBetween(String value1, String value2) {
            addCriterion("unit_manager between", value1, value2, "unitManager");
            return (Criteria) this;
        }

        public Criteria andUnitManagerNotBetween(String value1, String value2) {
            addCriterion("unit_manager not between", value1, value2, "unitManager");
            return (Criteria) this;
        }

        public Criteria andUnitAddressIsNull() {
            addCriterion("unit_address is null");
            return (Criteria) this;
        }

        public Criteria andUnitAddressIsNotNull() {
            addCriterion("unit_address is not null");
            return (Criteria) this;
        }

        public Criteria andUnitAddressEqualTo(String value) {
            addCriterion("unit_address =", value, "unitAddress");
            return (Criteria) this;
        }

        public Criteria andUnitAddressNotEqualTo(String value) {
            addCriterion("unit_address <>", value, "unitAddress");
            return (Criteria) this;
        }

        public Criteria andUnitAddressGreaterThan(String value) {
            addCriterion("unit_address >", value, "unitAddress");
            return (Criteria) this;
        }

        public Criteria andUnitAddressGreaterThanOrEqualTo(String value) {
            addCriterion("unit_address >=", value, "unitAddress");
            return (Criteria) this;
        }

        public Criteria andUnitAddressLessThan(String value) {
            addCriterion("unit_address <", value, "unitAddress");
            return (Criteria) this;
        }

        public Criteria andUnitAddressLessThanOrEqualTo(String value) {
            addCriterion("unit_address <=", value, "unitAddress");
            return (Criteria) this;
        }

        public Criteria andUnitAddressLike(String value) {
            addCriterion("unit_address like", value, "unitAddress");
            return (Criteria) this;
        }

        public Criteria andUnitAddressNotLike(String value) {
            addCriterion("unit_address not like", value, "unitAddress");
            return (Criteria) this;
        }

        public Criteria andUnitAddressIn(List<String> values) {
            addCriterion("unit_address in", values, "unitAddress");
            return (Criteria) this;
        }

        public Criteria andUnitAddressNotIn(List<String> values) {
            addCriterion("unit_address not in", values, "unitAddress");
            return (Criteria) this;
        }

        public Criteria andUnitAddressBetween(String value1, String value2) {
            addCriterion("unit_address between", value1, value2, "unitAddress");
            return (Criteria) this;
        }

        public Criteria andUnitAddressNotBetween(String value1, String value2) {
            addCriterion("unit_address not between", value1, value2, "unitAddress");
            return (Criteria) this;
        }

        public Criteria andUnitControlIsNull() {
            addCriterion("unit_control is null");
            return (Criteria) this;
        }

        public Criteria andUnitControlIsNotNull() {
            addCriterion("unit_control is not null");
            return (Criteria) this;
        }

        public Criteria andUnitControlEqualTo(String value) {
            addCriterion("unit_control =", value, "unitControl");
            return (Criteria) this;
        }

        public Criteria andUnitControlNotEqualTo(String value) {
            addCriterion("unit_control <>", value, "unitControl");
            return (Criteria) this;
        }

        public Criteria andUnitControlGreaterThan(String value) {
            addCriterion("unit_control >", value, "unitControl");
            return (Criteria) this;
        }

        public Criteria andUnitControlGreaterThanOrEqualTo(String value) {
            addCriterion("unit_control >=", value, "unitControl");
            return (Criteria) this;
        }

        public Criteria andUnitControlLessThan(String value) {
            addCriterion("unit_control <", value, "unitControl");
            return (Criteria) this;
        }

        public Criteria andUnitControlLessThanOrEqualTo(String value) {
            addCriterion("unit_control <=", value, "unitControl");
            return (Criteria) this;
        }

        public Criteria andUnitControlLike(String value) {
            addCriterion("unit_control like", value, "unitControl");
            return (Criteria) this;
        }

        public Criteria andUnitControlNotLike(String value) {
            addCriterion("unit_control not like", value, "unitControl");
            return (Criteria) this;
        }

        public Criteria andUnitControlIn(List<String> values) {
            addCriterion("unit_control in", values, "unitControl");
            return (Criteria) this;
        }

        public Criteria andUnitControlNotIn(List<String> values) {
            addCriterion("unit_control not in", values, "unitControl");
            return (Criteria) this;
        }

        public Criteria andUnitControlBetween(String value1, String value2) {
            addCriterion("unit_control between", value1, value2, "unitControl");
            return (Criteria) this;
        }

        public Criteria andUnitControlNotBetween(String value1, String value2) {
            addCriterion("unit_control not between", value1, value2, "unitControl");
            return (Criteria) this;
        }

        public Criteria andUnitAccountIsNull() {
            addCriterion("unit_account is null");
            return (Criteria) this;
        }

        public Criteria andUnitAccountIsNotNull() {
            addCriterion("unit_account is not null");
            return (Criteria) this;
        }

        public Criteria andUnitAccountEqualTo(String value) {
            addCriterion("unit_account =", value, "unitAccount");
            return (Criteria) this;
        }

        public Criteria andUnitAccountNotEqualTo(String value) {
            addCriterion("unit_account <>", value, "unitAccount");
            return (Criteria) this;
        }

        public Criteria andUnitAccountGreaterThan(String value) {
            addCriterion("unit_account >", value, "unitAccount");
            return (Criteria) this;
        }

        public Criteria andUnitAccountGreaterThanOrEqualTo(String value) {
            addCriterion("unit_account >=", value, "unitAccount");
            return (Criteria) this;
        }

        public Criteria andUnitAccountLessThan(String value) {
            addCriterion("unit_account <", value, "unitAccount");
            return (Criteria) this;
        }

        public Criteria andUnitAccountLessThanOrEqualTo(String value) {
            addCriterion("unit_account <=", value, "unitAccount");
            return (Criteria) this;
        }

        public Criteria andUnitAccountLike(String value) {
            addCriterion("unit_account like", value, "unitAccount");
            return (Criteria) this;
        }

        public Criteria andUnitAccountNotLike(String value) {
            addCriterion("unit_account not like", value, "unitAccount");
            return (Criteria) this;
        }

        public Criteria andUnitAccountIn(List<String> values) {
            addCriterion("unit_account in", values, "unitAccount");
            return (Criteria) this;
        }

        public Criteria andUnitAccountNotIn(List<String> values) {
            addCriterion("unit_account not in", values, "unitAccount");
            return (Criteria) this;
        }

        public Criteria andUnitAccountBetween(String value1, String value2) {
            addCriterion("unit_account between", value1, value2, "unitAccount");
            return (Criteria) this;
        }

        public Criteria andUnitAccountNotBetween(String value1, String value2) {
            addCriterion("unit_account not between", value1, value2, "unitAccount");
            return (Criteria) this;
        }

        public Criteria andUnitDelflagIsNull() {
            addCriterion("unit_delflag is null");
            return (Criteria) this;
        }

        public Criteria andUnitDelflagIsNotNull() {
            addCriterion("unit_delflag is not null");
            return (Criteria) this;
        }

        public Criteria andUnitDelflagEqualTo(Integer value) {
            addCriterion("unit_delflag =", value, "unitDelflag");
            return (Criteria) this;
        }

        public Criteria andUnitDelflagNotEqualTo(Integer value) {
            addCriterion("unit_delflag <>", value, "unitDelflag");
            return (Criteria) this;
        }

        public Criteria andUnitDelflagGreaterThan(Integer value) {
            addCriterion("unit_delflag >", value, "unitDelflag");
            return (Criteria) this;
        }

        public Criteria andUnitDelflagGreaterThanOrEqualTo(Integer value) {
            addCriterion("unit_delflag >=", value, "unitDelflag");
            return (Criteria) this;
        }

        public Criteria andUnitDelflagLessThan(Integer value) {
            addCriterion("unit_delflag <", value, "unitDelflag");
            return (Criteria) this;
        }

        public Criteria andUnitDelflagLessThanOrEqualTo(Integer value) {
            addCriterion("unit_delflag <=", value, "unitDelflag");
            return (Criteria) this;
        }

        public Criteria andUnitDelflagIn(List<Integer> values) {
            addCriterion("unit_delflag in", values, "unitDelflag");
            return (Criteria) this;
        }

        public Criteria andUnitDelflagNotIn(List<Integer> values) {
            addCriterion("unit_delflag not in", values, "unitDelflag");
            return (Criteria) this;
        }

        public Criteria andUnitDelflagBetween(Integer value1, Integer value2) {
            addCriterion("unit_delflag between", value1, value2, "unitDelflag");
            return (Criteria) this;
        }

        public Criteria andUnitDelflagNotBetween(Integer value1, Integer value2) {
            addCriterion("unit_delflag not between", value1, value2, "unitDelflag");
            return (Criteria) this;
        }

        public Criteria andUnitLevelIsNull() {
            addCriterion("unit_level is null");
            return (Criteria) this;
        }

        public Criteria andUnitLevelIsNotNull() {
            addCriterion("unit_level is not null");
            return (Criteria) this;
        }

        public Criteria andUnitLevelEqualTo(Integer value) {
            addCriterion("unit_level =", value, "unitLevel");
            return (Criteria) this;
        }

        public Criteria andUnitLevelNotEqualTo(Integer value) {
            addCriterion("unit_level <>", value, "unitLevel");
            return (Criteria) this;
        }

        public Criteria andUnitLevelGreaterThan(Integer value) {
            addCriterion("unit_level >", value, "unitLevel");
            return (Criteria) this;
        }

        public Criteria andUnitLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("unit_level >=", value, "unitLevel");
            return (Criteria) this;
        }

        public Criteria andUnitLevelLessThan(Integer value) {
            addCriterion("unit_level <", value, "unitLevel");
            return (Criteria) this;
        }

        public Criteria andUnitLevelLessThanOrEqualTo(Integer value) {
            addCriterion("unit_level <=", value, "unitLevel");
            return (Criteria) this;
        }

        public Criteria andUnitLevelIn(List<Integer> values) {
            addCriterion("unit_level in", values, "unitLevel");
            return (Criteria) this;
        }

        public Criteria andUnitLevelNotIn(List<Integer> values) {
            addCriterion("unit_level not in", values, "unitLevel");
            return (Criteria) this;
        }

        public Criteria andUnitLevelBetween(Integer value1, Integer value2) {
            addCriterion("unit_level between", value1, value2, "unitLevel");
            return (Criteria) this;
        }

        public Criteria andUnitLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("unit_level not between", value1, value2, "unitLevel");
            return (Criteria) this;
        }

        public Criteria andUnitRelationIsNull() {
            addCriterion("unit_relation is null");
            return (Criteria) this;
        }

        public Criteria andUnitRelationIsNotNull() {
            addCriterion("unit_relation is not null");
            return (Criteria) this;
        }

        public Criteria andUnitRelationEqualTo(String value) {
            addCriterion("unit_relation =", value, "unitRelation");
            return (Criteria) this;
        }

        public Criteria andUnitRelationNotEqualTo(String value) {
            addCriterion("unit_relation <>", value, "unitRelation");
            return (Criteria) this;
        }

        public Criteria andUnitRelationGreaterThan(String value) {
            addCriterion("unit_relation >", value, "unitRelation");
            return (Criteria) this;
        }

        public Criteria andUnitRelationGreaterThanOrEqualTo(String value) {
            addCriterion("unit_relation >=", value, "unitRelation");
            return (Criteria) this;
        }

        public Criteria andUnitRelationLessThan(String value) {
            addCriterion("unit_relation <", value, "unitRelation");
            return (Criteria) this;
        }

        public Criteria andUnitRelationLessThanOrEqualTo(String value) {
            addCriterion("unit_relation <=", value, "unitRelation");
            return (Criteria) this;
        }

        public Criteria andUnitRelationLike(String value) {
            addCriterion("unit_relation like", value, "unitRelation");
            return (Criteria) this;
        }

        public Criteria andUnitRelationNotLike(String value) {
            addCriterion("unit_relation not like", value, "unitRelation");
            return (Criteria) this;
        }

        public Criteria andUnitRelationIn(List<String> values) {
            addCriterion("unit_relation in", values, "unitRelation");
            return (Criteria) this;
        }

        public Criteria andUnitRelationNotIn(List<String> values) {
            addCriterion("unit_relation not in", values, "unitRelation");
            return (Criteria) this;
        }

        public Criteria andUnitRelationBetween(String value1, String value2) {
            addCriterion("unit_relation between", value1, value2, "unitRelation");
            return (Criteria) this;
        }

        public Criteria andUnitRelationNotBetween(String value1, String value2) {
            addCriterion("unit_relation not between", value1, value2, "unitRelation");
            return (Criteria) this;
        }

        public Criteria andUnitPathIsNull() {
            addCriterion("unit_path is null");
            return (Criteria) this;
        }

        public Criteria andUnitPathIsNotNull() {
            addCriterion("unit_path is not null");
            return (Criteria) this;
        }

        public Criteria andUnitPathEqualTo(String value) {
            addCriterion("unit_path =", value, "unitPath");
            return (Criteria) this;
        }

        public Criteria andUnitPathNotEqualTo(String value) {
            addCriterion("unit_path <>", value, "unitPath");
            return (Criteria) this;
        }

        public Criteria andUnitPathGreaterThan(String value) {
            addCriterion("unit_path >", value, "unitPath");
            return (Criteria) this;
        }

        public Criteria andUnitPathGreaterThanOrEqualTo(String value) {
            addCriterion("unit_path >=", value, "unitPath");
            return (Criteria) this;
        }

        public Criteria andUnitPathLessThan(String value) {
            addCriterion("unit_path <", value, "unitPath");
            return (Criteria) this;
        }

        public Criteria andUnitPathLessThanOrEqualTo(String value) {
            addCriterion("unit_path <=", value, "unitPath");
            return (Criteria) this;
        }

        public Criteria andUnitPathLike(String value) {
            addCriterion("unit_path like", value, "unitPath");
            return (Criteria) this;
        }

        public Criteria andUnitPathNotLike(String value) {
            addCriterion("unit_path not like", value, "unitPath");
            return (Criteria) this;
        }

        public Criteria andUnitPathIn(List<String> values) {
            addCriterion("unit_path in", values, "unitPath");
            return (Criteria) this;
        }

        public Criteria andUnitPathNotIn(List<String> values) {
            addCriterion("unit_path not in", values, "unitPath");
            return (Criteria) this;
        }

        public Criteria andUnitPathBetween(String value1, String value2) {
            addCriterion("unit_path between", value1, value2, "unitPath");
            return (Criteria) this;
        }

        public Criteria andUnitPathNotBetween(String value1, String value2) {
            addCriterion("unit_path not between", value1, value2, "unitPath");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_unit
     *
     * @mbg.generated do_not_delete_during_merge Fri Apr 13 16:40:44 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_unit
     *
     * @mbg.generated Fri Apr 13 16:40:44 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}