package com.pcitc.base.workflow;

import java.util.Date;

public class SysTaskDelegate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_task_delegate.task_delegate_id
     *
     * @mbggenerated Sun May 13 17:36:39 CST 2018
     */
    private String taskDelegateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_task_delegate.task_id
     *
     * @mbggenerated Sun May 13 17:36:39 CST 2018
     */
    private String taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_task_delegate.delegate_id
     *
     * @mbggenerated Sun May 13 17:36:39 CST 2018
     */
    private String delegateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_task_delegate.status
     *
     * @mbggenerated Sun May 13 17:36:39 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_task_delegate.create_date
     *
     * @mbggenerated Sun May 13 17:36:39 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_task_delegate.remarks
     *
     * @mbggenerated Sun May 13 17:36:39 CST 2018
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_task_delegate.task_delegate_id
     *
     * @return the value of sys_task_delegate.task_delegate_id
     *
     * @mbggenerated Sun May 13 17:36:39 CST 2018
     */
    public String getTaskDelegateId() {
        return taskDelegateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_task_delegate.task_delegate_id
     *
     * @param taskDelegateId the value for sys_task_delegate.task_delegate_id
     *
     * @mbggenerated Sun May 13 17:36:39 CST 2018
     */
    public void setTaskDelegateId(String taskDelegateId) {
        this.taskDelegateId = taskDelegateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_task_delegate.task_id
     *
     * @return the value of sys_task_delegate.task_id
     *
     * @mbggenerated Sun May 13 17:36:39 CST 2018
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_task_delegate.task_id
     *
     * @param taskId the value for sys_task_delegate.task_id
     *
     * @mbggenerated Sun May 13 17:36:39 CST 2018
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_task_delegate.delegate_id
     *
     * @return the value of sys_task_delegate.delegate_id
     *
     * @mbggenerated Sun May 13 17:36:39 CST 2018
     */
    public String getDelegateId() {
        return delegateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_task_delegate.delegate_id
     *
     * @param delegateId the value for sys_task_delegate.delegate_id
     *
     * @mbggenerated Sun May 13 17:36:39 CST 2018
     */
    public void setDelegateId(String delegateId) {
        this.delegateId = delegateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_task_delegate.status
     *
     * @return the value of sys_task_delegate.status
     *
     * @mbggenerated Sun May 13 17:36:39 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_task_delegate.status
     *
     * @param status the value for sys_task_delegate.status
     *
     * @mbggenerated Sun May 13 17:36:39 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_task_delegate.create_date
     *
     * @return the value of sys_task_delegate.create_date
     *
     * @mbggenerated Sun May 13 17:36:39 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_task_delegate.create_date
     *
     * @param createDate the value for sys_task_delegate.create_date
     *
     * @mbggenerated Sun May 13 17:36:39 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_task_delegate.remarks
     *
     * @return the value of sys_task_delegate.remarks
     *
     * @mbggenerated Sun May 13 17:36:39 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_task_delegate.remarks
     *
     * @param remarks the value for sys_task_delegate.remarks
     *
     * @mbggenerated Sun May 13 17:36:39 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
}