package com.pcitc.base.engin.construct.constructProcess;

import java.io.Serializable;

import com.pcitc.base.util.SearchInfo;

public class EngineeringMoratoriumVo extends SearchInfo implements Serializable{
	
	private static final long serialVersionUID = 1L;
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_engineering_moratorium.data_id
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    private String dataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_engineering_moratorium.create_user
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_engineering_moratorium.create_date
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_engineering_moratorium.update_user
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_engineering_moratorium.update_date
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_engineering_moratorium.status
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_engineering_moratorium.audit_status
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    private String auditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_engineering_moratorium.company_code
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    private String companyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_engineering_moratorium.project_id
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    private String projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_engineering_moratorium.form_code
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    private String formCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_engineering_moratorium.single_project_name
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    private String singleProjectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_engineering_moratorium.single_project_code
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    private String singleProjectCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_engineering_moratorium.contractor_unit_name
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    private String contractorUnitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_engineering_moratorium.contractor_unit_code
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    private String contractorUnitCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_engineering_moratorium.supervisor_unit_name
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    private String supervisorUnitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_engineering_moratorium.supervisor_unit_code
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    private String supervisorUnitCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_engineering_moratorium.shutdown_days
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    private String shutdownDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_engineering_moratorium.shutdown_start_time
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    private String shutdownStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_engineering_moratorium.shutdown_end_time
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    private String shutdownEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_engineering_moratorium.shutdown_cause
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    private String shutdownCause;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_engineering_moratorium.data_id
     *
     * @return the value of construct_engineering_moratorium.data_id
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public String getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_engineering_moratorium.data_id
     *
     * @param dataId the value for construct_engineering_moratorium.data_id
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public void setDataId(String dataId) {
        this.dataId = dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_engineering_moratorium.create_user
     *
     * @return the value of construct_engineering_moratorium.create_user
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_engineering_moratorium.create_user
     *
     * @param createUser the value for construct_engineering_moratorium.create_user
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_engineering_moratorium.create_date
     *
     * @return the value of construct_engineering_moratorium.create_date
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_engineering_moratorium.create_date
     *
     * @param createDate the value for construct_engineering_moratorium.create_date
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_engineering_moratorium.update_user
     *
     * @return the value of construct_engineering_moratorium.update_user
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_engineering_moratorium.update_user
     *
     * @param updateUser the value for construct_engineering_moratorium.update_user
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_engineering_moratorium.update_date
     *
     * @return the value of construct_engineering_moratorium.update_date
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_engineering_moratorium.update_date
     *
     * @param updateDate the value for construct_engineering_moratorium.update_date
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_engineering_moratorium.status
     *
     * @return the value of construct_engineering_moratorium.status
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_engineering_moratorium.status
     *
     * @param status the value for construct_engineering_moratorium.status
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_engineering_moratorium.audit_status
     *
     * @return the value of construct_engineering_moratorium.audit_status
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public String getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_engineering_moratorium.audit_status
     *
     * @param auditStatus the value for construct_engineering_moratorium.audit_status
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public void setAuditStatus(String auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_engineering_moratorium.company_code
     *
     * @return the value of construct_engineering_moratorium.company_code
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_engineering_moratorium.company_code
     *
     * @param companyCode the value for construct_engineering_moratorium.company_code
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_engineering_moratorium.project_id
     *
     * @return the value of construct_engineering_moratorium.project_id
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_engineering_moratorium.project_id
     *
     * @param projectId the value for construct_engineering_moratorium.project_id
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_engineering_moratorium.form_code
     *
     * @return the value of construct_engineering_moratorium.form_code
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public String getFormCode() {
        return formCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_engineering_moratorium.form_code
     *
     * @param formCode the value for construct_engineering_moratorium.form_code
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public void setFormCode(String formCode) {
        this.formCode = formCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_engineering_moratorium.single_project_name
     *
     * @return the value of construct_engineering_moratorium.single_project_name
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public String getSingleProjectName() {
        return singleProjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_engineering_moratorium.single_project_name
     *
     * @param singleProjectName the value for construct_engineering_moratorium.single_project_name
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public void setSingleProjectName(String singleProjectName) {
        this.singleProjectName = singleProjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_engineering_moratorium.single_project_code
     *
     * @return the value of construct_engineering_moratorium.single_project_code
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public String getSingleProjectCode() {
        return singleProjectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_engineering_moratorium.single_project_code
     *
     * @param singleProjectCode the value for construct_engineering_moratorium.single_project_code
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public void setSingleProjectCode(String singleProjectCode) {
        this.singleProjectCode = singleProjectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_engineering_moratorium.contractor_unit_name
     *
     * @return the value of construct_engineering_moratorium.contractor_unit_name
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public String getContractorUnitName() {
        return contractorUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_engineering_moratorium.contractor_unit_name
     *
     * @param contractorUnitName the value for construct_engineering_moratorium.contractor_unit_name
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public void setContractorUnitName(String contractorUnitName) {
        this.contractorUnitName = contractorUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_engineering_moratorium.contractor_unit_code
     *
     * @return the value of construct_engineering_moratorium.contractor_unit_code
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public String getContractorUnitCode() {
        return contractorUnitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_engineering_moratorium.contractor_unit_code
     *
     * @param contractorUnitCode the value for construct_engineering_moratorium.contractor_unit_code
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public void setContractorUnitCode(String contractorUnitCode) {
        this.contractorUnitCode = contractorUnitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_engineering_moratorium.supervisor_unit_name
     *
     * @return the value of construct_engineering_moratorium.supervisor_unit_name
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public String getSupervisorUnitName() {
        return supervisorUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_engineering_moratorium.supervisor_unit_name
     *
     * @param supervisorUnitName the value for construct_engineering_moratorium.supervisor_unit_name
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public void setSupervisorUnitName(String supervisorUnitName) {
        this.supervisorUnitName = supervisorUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_engineering_moratorium.supervisor_unit_code
     *
     * @return the value of construct_engineering_moratorium.supervisor_unit_code
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public String getSupervisorUnitCode() {
        return supervisorUnitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_engineering_moratorium.supervisor_unit_code
     *
     * @param supervisorUnitCode the value for construct_engineering_moratorium.supervisor_unit_code
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public void setSupervisorUnitCode(String supervisorUnitCode) {
        this.supervisorUnitCode = supervisorUnitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_engineering_moratorium.shutdown_days
     *
     * @return the value of construct_engineering_moratorium.shutdown_days
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public String getShutdownDays() {
        return shutdownDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_engineering_moratorium.shutdown_days
     *
     * @param shutdownDays the value for construct_engineering_moratorium.shutdown_days
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public void setShutdownDays(String shutdownDays) {
        this.shutdownDays = shutdownDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_engineering_moratorium.shutdown_start_time
     *
     * @return the value of construct_engineering_moratorium.shutdown_start_time
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public String getShutdownStartTime() {
        return shutdownStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_engineering_moratorium.shutdown_start_time
     *
     * @param shutdownStartTime the value for construct_engineering_moratorium.shutdown_start_time
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public void setShutdownStartTime(String shutdownStartTime) {
        this.shutdownStartTime = shutdownStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_engineering_moratorium.shutdown_end_time
     *
     * @return the value of construct_engineering_moratorium.shutdown_end_time
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public String getShutdownEndTime() {
        return shutdownEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_engineering_moratorium.shutdown_end_time
     *
     * @param shutdownEndTime the value for construct_engineering_moratorium.shutdown_end_time
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public void setShutdownEndTime(String shutdownEndTime) {
        this.shutdownEndTime = shutdownEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_engineering_moratorium.shutdown_cause
     *
     * @return the value of construct_engineering_moratorium.shutdown_cause
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public String getShutdownCause() {
        return shutdownCause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_engineering_moratorium.shutdown_cause
     *
     * @param shutdownCause the value for construct_engineering_moratorium.shutdown_cause
     *
     * @mbggenerated Wed Oct 10 16:07:25 CST 2018
     */
    public void setShutdownCause(String shutdownCause) {
        this.shutdownCause = shutdownCause;
    }
}