package com.pcitc.base.engin.construct.constructProcess;

import java.io.Serializable;

import com.pcitc.base.util.SearchInfo;

public class MonthEngineerImplPlanDetail extends SearchInfo implements Serializable{
	
	private static final long serialVersionUID = 1L;
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan_detail.data_id
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    private String dataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan_detail.create_user
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan_detail.create_date
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan_detail.update_user
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan_detail.update_date
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan_detail.status
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan_detail.audit_status
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    private String auditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan_detail.company_code
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    private String companyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan_detail.project_id
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    private String projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan_detail.form_code
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    private String formCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan_detail.engineering_name
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    private String engineeringName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan_detail.measurement_unit
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    private String measurementUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan_detail.design_quantity
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    private String designQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan_detail.actual_completion
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    private String actualCompletion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan_detail.accumulative_completion
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    private String accumulativeCompletion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan_detail.plan
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    private String plan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan_detail.implplan_id
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    private String implplanId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan_detail.data_id
     *
     * @return the value of construct_month_engineer_implplan_detail.data_id
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    public String getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan_detail.data_id
     *
     * @param dataId the value for construct_month_engineer_implplan_detail.data_id
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    public void setDataId(String dataId) {
        this.dataId = dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan_detail.create_user
     *
     * @return the value of construct_month_engineer_implplan_detail.create_user
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan_detail.create_user
     *
     * @param createUser the value for construct_month_engineer_implplan_detail.create_user
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan_detail.create_date
     *
     * @return the value of construct_month_engineer_implplan_detail.create_date
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan_detail.create_date
     *
     * @param createDate the value for construct_month_engineer_implplan_detail.create_date
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan_detail.update_user
     *
     * @return the value of construct_month_engineer_implplan_detail.update_user
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan_detail.update_user
     *
     * @param updateUser the value for construct_month_engineer_implplan_detail.update_user
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan_detail.update_date
     *
     * @return the value of construct_month_engineer_implplan_detail.update_date
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan_detail.update_date
     *
     * @param updateDate the value for construct_month_engineer_implplan_detail.update_date
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan_detail.status
     *
     * @return the value of construct_month_engineer_implplan_detail.status
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan_detail.status
     *
     * @param status the value for construct_month_engineer_implplan_detail.status
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan_detail.audit_status
     *
     * @return the value of construct_month_engineer_implplan_detail.audit_status
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    public String getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan_detail.audit_status
     *
     * @param auditStatus the value for construct_month_engineer_implplan_detail.audit_status
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    public void setAuditStatus(String auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan_detail.company_code
     *
     * @return the value of construct_month_engineer_implplan_detail.company_code
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan_detail.company_code
     *
     * @param companyCode the value for construct_month_engineer_implplan_detail.company_code
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan_detail.project_id
     *
     * @return the value of construct_month_engineer_implplan_detail.project_id
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan_detail.project_id
     *
     * @param projectId the value for construct_month_engineer_implplan_detail.project_id
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan_detail.form_code
     *
     * @return the value of construct_month_engineer_implplan_detail.form_code
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    public String getFormCode() {
        return formCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan_detail.form_code
     *
     * @param formCode the value for construct_month_engineer_implplan_detail.form_code
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    public void setFormCode(String formCode) {
        this.formCode = formCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan_detail.engineering_name
     *
     * @return the value of construct_month_engineer_implplan_detail.engineering_name
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    public String getEngineeringName() {
        return engineeringName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan_detail.engineering_name
     *
     * @param engineeringName the value for construct_month_engineer_implplan_detail.engineering_name
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    public void setEngineeringName(String engineeringName) {
        this.engineeringName = engineeringName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan_detail.measurement_unit
     *
     * @return the value of construct_month_engineer_implplan_detail.measurement_unit
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    public String getMeasurementUnit() {
        return measurementUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan_detail.measurement_unit
     *
     * @param measurementUnit the value for construct_month_engineer_implplan_detail.measurement_unit
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    public void setMeasurementUnit(String measurementUnit) {
        this.measurementUnit = measurementUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan_detail.design_quantity
     *
     * @return the value of construct_month_engineer_implplan_detail.design_quantity
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    public String getDesignQuantity() {
        return designQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan_detail.design_quantity
     *
     * @param designQuantity the value for construct_month_engineer_implplan_detail.design_quantity
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    public void setDesignQuantity(String designQuantity) {
        this.designQuantity = designQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan_detail.actual_completion
     *
     * @return the value of construct_month_engineer_implplan_detail.actual_completion
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    public String getActualCompletion() {
        return actualCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan_detail.actual_completion
     *
     * @param actualCompletion the value for construct_month_engineer_implplan_detail.actual_completion
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    public void setActualCompletion(String actualCompletion) {
        this.actualCompletion = actualCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan_detail.accumulative_completion
     *
     * @return the value of construct_month_engineer_implplan_detail.accumulative_completion
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    public String getAccumulativeCompletion() {
        return accumulativeCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan_detail.accumulative_completion
     *
     * @param accumulativeCompletion the value for construct_month_engineer_implplan_detail.accumulative_completion
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    public void setAccumulativeCompletion(String accumulativeCompletion) {
        this.accumulativeCompletion = accumulativeCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan_detail.plan
     *
     * @return the value of construct_month_engineer_implplan_detail.plan
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    public String getPlan() {
        return plan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan_detail.plan
     *
     * @param plan the value for construct_month_engineer_implplan_detail.plan
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    public void setPlan(String plan) {
        this.plan = plan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan_detail.implplan_id
     *
     * @return the value of construct_month_engineer_implplan_detail.implplan_id
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    public String getImplplanId() {
        return implplanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan_detail.implplan_id
     *
     * @param implplanId the value for construct_month_engineer_implplan_detail.implplan_id
     *
     * @mbggenerated Thu Sep 06 14:07:00 CST 2018
     */
    public void setImplplanId(String implplanId) {
        this.implplanId = implplanId;
    }
}