package com.pcitc.base.engin.construct.constructProcess;

import java.io.Serializable;
import java.util.List;

import com.pcitc.base.util.SearchInfo;

public class MonthEngineerImplPlan extends SearchInfo implements Serializable{
	
	private static final long serialVersionUID = 1L;
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.data_id
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String dataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.create_user
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.create_date
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.update_user
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.update_date
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.status
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.audit_status
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String auditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.company_code
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String companyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.project_id
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.form_code
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String formCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.single_project_name
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String singleProjectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.single_project_code
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String singleProjectCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.construct_unit_name
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String constructUnitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.construct_unit_code
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String constructUnitCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.supervisor_unit_name
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String supervisorUnitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.supervisor_unit_code
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String supervisorUnitCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.project_department_name
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String projectDepartmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.project_department_code
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String projectDepartmentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.plan_month
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String planMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.edit_month
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String editMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.equipment_actual_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String equipmentActualCompletion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.equipment_plan_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String equipmentPlanCompletion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.equipment_accumulative_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String equipmentAccumulativeCompletion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.material_actual_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String materialActualCompletion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.material_plan_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String materialPlanCompletion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.material_accumulative_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String materialAccumulativeCompletion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.architecture_actual_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String architectureActualCompletion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.architecture_plan_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String architecturePlanCompletion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.architecture_accumulative_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String architectureAccumulativeCompletion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.install_actual_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String installActualCompletion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.install_plan_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String installPlanCompletion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.install_accumulative_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String installAccumulativeCompletion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.other_actual_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String otherActualCompletion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.other_plan_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String otherPlanCompletion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.other_accumulative_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String otherAccumulativeCompletion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.total_actual_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String totalActualCompletion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.total_plan_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String totalPlanCompletion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_implplan.total_accumulative_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    private String totalAccumulativeCompletion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.data_id
     *
     * @return the value of construct_month_engineer_implplan.data_id
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    
    private List<MonthEngineerImplPlanDetail> monthEngineerImplPlanDetails;
    
    public String getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.data_id
     *
     * @param dataId the value for construct_month_engineer_implplan.data_id
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setDataId(String dataId) {
        this.dataId = dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.create_user
     *
     * @return the value of construct_month_engineer_implplan.create_user
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.create_user
     *
     * @param createUser the value for construct_month_engineer_implplan.create_user
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.create_date
     *
     * @return the value of construct_month_engineer_implplan.create_date
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.create_date
     *
     * @param createDate the value for construct_month_engineer_implplan.create_date
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.update_user
     *
     * @return the value of construct_month_engineer_implplan.update_user
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.update_user
     *
     * @param updateUser the value for construct_month_engineer_implplan.update_user
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.update_date
     *
     * @return the value of construct_month_engineer_implplan.update_date
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.update_date
     *
     * @param updateDate the value for construct_month_engineer_implplan.update_date
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.status
     *
     * @return the value of construct_month_engineer_implplan.status
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.status
     *
     * @param status the value for construct_month_engineer_implplan.status
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.audit_status
     *
     * @return the value of construct_month_engineer_implplan.audit_status
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.audit_status
     *
     * @param auditStatus the value for construct_month_engineer_implplan.audit_status
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setAuditStatus(String auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.company_code
     *
     * @return the value of construct_month_engineer_implplan.company_code
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.company_code
     *
     * @param companyCode the value for construct_month_engineer_implplan.company_code
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.project_id
     *
     * @return the value of construct_month_engineer_implplan.project_id
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.project_id
     *
     * @param projectId the value for construct_month_engineer_implplan.project_id
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.form_code
     *
     * @return the value of construct_month_engineer_implplan.form_code
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getFormCode() {
        return formCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.form_code
     *
     * @param formCode the value for construct_month_engineer_implplan.form_code
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setFormCode(String formCode) {
        this.formCode = formCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.single_project_name
     *
     * @return the value of construct_month_engineer_implplan.single_project_name
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getSingleProjectName() {
        return singleProjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.single_project_name
     *
     * @param singleProjectName the value for construct_month_engineer_implplan.single_project_name
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setSingleProjectName(String singleProjectName) {
        this.singleProjectName = singleProjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.single_project_code
     *
     * @return the value of construct_month_engineer_implplan.single_project_code
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getSingleProjectCode() {
        return singleProjectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.single_project_code
     *
     * @param singleProjectCode the value for construct_month_engineer_implplan.single_project_code
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setSingleProjectCode(String singleProjectCode) {
        this.singleProjectCode = singleProjectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.construct_unit_name
     *
     * @return the value of construct_month_engineer_implplan.construct_unit_name
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getConstructUnitName() {
        return constructUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.construct_unit_name
     *
     * @param constructUnitName the value for construct_month_engineer_implplan.construct_unit_name
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setConstructUnitName(String constructUnitName) {
        this.constructUnitName = constructUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.construct_unit_code
     *
     * @return the value of construct_month_engineer_implplan.construct_unit_code
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getConstructUnitCode() {
        return constructUnitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.construct_unit_code
     *
     * @param constructUnitCode the value for construct_month_engineer_implplan.construct_unit_code
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setConstructUnitCode(String constructUnitCode) {
        this.constructUnitCode = constructUnitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.supervisor_unit_name
     *
     * @return the value of construct_month_engineer_implplan.supervisor_unit_name
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getSupervisorUnitName() {
        return supervisorUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.supervisor_unit_name
     *
     * @param supervisorUnitName the value for construct_month_engineer_implplan.supervisor_unit_name
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setSupervisorUnitName(String supervisorUnitName) {
        this.supervisorUnitName = supervisorUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.supervisor_unit_code
     *
     * @return the value of construct_month_engineer_implplan.supervisor_unit_code
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getSupervisorUnitCode() {
        return supervisorUnitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.supervisor_unit_code
     *
     * @param supervisorUnitCode the value for construct_month_engineer_implplan.supervisor_unit_code
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setSupervisorUnitCode(String supervisorUnitCode) {
        this.supervisorUnitCode = supervisorUnitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.project_department_name
     *
     * @return the value of construct_month_engineer_implplan.project_department_name
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getProjectDepartmentName() {
        return projectDepartmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.project_department_name
     *
     * @param projectDepartmentName the value for construct_month_engineer_implplan.project_department_name
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setProjectDepartmentName(String projectDepartmentName) {
        this.projectDepartmentName = projectDepartmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.project_department_code
     *
     * @return the value of construct_month_engineer_implplan.project_department_code
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getProjectDepartmentCode() {
        return projectDepartmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.project_department_code
     *
     * @param projectDepartmentCode the value for construct_month_engineer_implplan.project_department_code
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setProjectDepartmentCode(String projectDepartmentCode) {
        this.projectDepartmentCode = projectDepartmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.plan_month
     *
     * @return the value of construct_month_engineer_implplan.plan_month
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getPlanMonth() {
        return planMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.plan_month
     *
     * @param planMonth the value for construct_month_engineer_implplan.plan_month
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setPlanMonth(String planMonth) {
        this.planMonth = planMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.edit_month
     *
     * @return the value of construct_month_engineer_implplan.edit_month
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getEditMonth() {
        return editMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.edit_month
     *
     * @param editMonth the value for construct_month_engineer_implplan.edit_month
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setEditMonth(String editMonth) {
        this.editMonth = editMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.equipment_actual_completion
     *
     * @return the value of construct_month_engineer_implplan.equipment_actual_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getEquipmentActualCompletion() {
        return equipmentActualCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.equipment_actual_completion
     *
     * @param equipmentActualCompletion the value for construct_month_engineer_implplan.equipment_actual_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setEquipmentActualCompletion(String equipmentActualCompletion) {
        this.equipmentActualCompletion = equipmentActualCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.equipment_plan_completion
     *
     * @return the value of construct_month_engineer_implplan.equipment_plan_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getEquipmentPlanCompletion() {
        return equipmentPlanCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.equipment_plan_completion
     *
     * @param equipmentPlanCompletion the value for construct_month_engineer_implplan.equipment_plan_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setEquipmentPlanCompletion(String equipmentPlanCompletion) {
        this.equipmentPlanCompletion = equipmentPlanCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.equipment_accumulative_completion
     *
     * @return the value of construct_month_engineer_implplan.equipment_accumulative_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getEquipmentAccumulativeCompletion() {
        return equipmentAccumulativeCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.equipment_accumulative_completion
     *
     * @param equipmentAccumulativeCompletion the value for construct_month_engineer_implplan.equipment_accumulative_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setEquipmentAccumulativeCompletion(String equipmentAccumulativeCompletion) {
        this.equipmentAccumulativeCompletion = equipmentAccumulativeCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.material_actual_completion
     *
     * @return the value of construct_month_engineer_implplan.material_actual_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getMaterialActualCompletion() {
        return materialActualCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.material_actual_completion
     *
     * @param materialActualCompletion the value for construct_month_engineer_implplan.material_actual_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setMaterialActualCompletion(String materialActualCompletion) {
        this.materialActualCompletion = materialActualCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.material_plan_completion
     *
     * @return the value of construct_month_engineer_implplan.material_plan_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getMaterialPlanCompletion() {
        return materialPlanCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.material_plan_completion
     *
     * @param materialPlanCompletion the value for construct_month_engineer_implplan.material_plan_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setMaterialPlanCompletion(String materialPlanCompletion) {
        this.materialPlanCompletion = materialPlanCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.material_accumulative_completion
     *
     * @return the value of construct_month_engineer_implplan.material_accumulative_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getMaterialAccumulativeCompletion() {
        return materialAccumulativeCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.material_accumulative_completion
     *
     * @param materialAccumulativeCompletion the value for construct_month_engineer_implplan.material_accumulative_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setMaterialAccumulativeCompletion(String materialAccumulativeCompletion) {
        this.materialAccumulativeCompletion = materialAccumulativeCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.architecture_actual_completion
     *
     * @return the value of construct_month_engineer_implplan.architecture_actual_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getArchitectureActualCompletion() {
        return architectureActualCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.architecture_actual_completion
     *
     * @param architectureActualCompletion the value for construct_month_engineer_implplan.architecture_actual_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setArchitectureActualCompletion(String architectureActualCompletion) {
        this.architectureActualCompletion = architectureActualCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.architecture_plan_completion
     *
     * @return the value of construct_month_engineer_implplan.architecture_plan_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getArchitecturePlanCompletion() {
        return architecturePlanCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.architecture_plan_completion
     *
     * @param architecturePlanCompletion the value for construct_month_engineer_implplan.architecture_plan_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setArchitecturePlanCompletion(String architecturePlanCompletion) {
        this.architecturePlanCompletion = architecturePlanCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.architecture_accumulative_completion
     *
     * @return the value of construct_month_engineer_implplan.architecture_accumulative_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getArchitectureAccumulativeCompletion() {
        return architectureAccumulativeCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.architecture_accumulative_completion
     *
     * @param architectureAccumulativeCompletion the value for construct_month_engineer_implplan.architecture_accumulative_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setArchitectureAccumulativeCompletion(String architectureAccumulativeCompletion) {
        this.architectureAccumulativeCompletion = architectureAccumulativeCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.install_actual_completion
     *
     * @return the value of construct_month_engineer_implplan.install_actual_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getInstallActualCompletion() {
        return installActualCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.install_actual_completion
     *
     * @param installActualCompletion the value for construct_month_engineer_implplan.install_actual_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setInstallActualCompletion(String installActualCompletion) {
        this.installActualCompletion = installActualCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.install_plan_completion
     *
     * @return the value of construct_month_engineer_implplan.install_plan_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getInstallPlanCompletion() {
        return installPlanCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.install_plan_completion
     *
     * @param installPlanCompletion the value for construct_month_engineer_implplan.install_plan_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setInstallPlanCompletion(String installPlanCompletion) {
        this.installPlanCompletion = installPlanCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.install_accumulative_completion
     *
     * @return the value of construct_month_engineer_implplan.install_accumulative_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getInstallAccumulativeCompletion() {
        return installAccumulativeCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.install_accumulative_completion
     *
     * @param installAccumulativeCompletion the value for construct_month_engineer_implplan.install_accumulative_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setInstallAccumulativeCompletion(String installAccumulativeCompletion) {
        this.installAccumulativeCompletion = installAccumulativeCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.other_actual_completion
     *
     * @return the value of construct_month_engineer_implplan.other_actual_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getOtherActualCompletion() {
        return otherActualCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.other_actual_completion
     *
     * @param otherActualCompletion the value for construct_month_engineer_implplan.other_actual_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setOtherActualCompletion(String otherActualCompletion) {
        this.otherActualCompletion = otherActualCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.other_plan_completion
     *
     * @return the value of construct_month_engineer_implplan.other_plan_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getOtherPlanCompletion() {
        return otherPlanCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.other_plan_completion
     *
     * @param otherPlanCompletion the value for construct_month_engineer_implplan.other_plan_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setOtherPlanCompletion(String otherPlanCompletion) {
        this.otherPlanCompletion = otherPlanCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.other_accumulative_completion
     *
     * @return the value of construct_month_engineer_implplan.other_accumulative_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getOtherAccumulativeCompletion() {
        return otherAccumulativeCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.other_accumulative_completion
     *
     * @param otherAccumulativeCompletion the value for construct_month_engineer_implplan.other_accumulative_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setOtherAccumulativeCompletion(String otherAccumulativeCompletion) {
        this.otherAccumulativeCompletion = otherAccumulativeCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.total_actual_completion
     *
     * @return the value of construct_month_engineer_implplan.total_actual_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getTotalActualCompletion() {
        return totalActualCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.total_actual_completion
     *
     * @param totalActualCompletion the value for construct_month_engineer_implplan.total_actual_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setTotalActualCompletion(String totalActualCompletion) {
        this.totalActualCompletion = totalActualCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.total_plan_completion
     *
     * @return the value of construct_month_engineer_implplan.total_plan_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getTotalPlanCompletion() {
        return totalPlanCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.total_plan_completion
     *
     * @param totalPlanCompletion the value for construct_month_engineer_implplan.total_plan_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setTotalPlanCompletion(String totalPlanCompletion) {
        this.totalPlanCompletion = totalPlanCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_implplan.total_accumulative_completion
     *
     * @return the value of construct_month_engineer_implplan.total_accumulative_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public String getTotalAccumulativeCompletion() {
        return totalAccumulativeCompletion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_implplan.total_accumulative_completion
     *
     * @param totalAccumulativeCompletion the value for construct_month_engineer_implplan.total_accumulative_completion
     *
     * @mbggenerated Mon Sep 03 15:22:57 CST 2018
     */
    public void setTotalAccumulativeCompletion(String totalAccumulativeCompletion) {
        this.totalAccumulativeCompletion = totalAccumulativeCompletion;
    }

	public List<MonthEngineerImplPlanDetail> getMonthEngineerImplPlanDetails() {
		return monthEngineerImplPlanDetails;
	}

	public void setMonthEngineerImplPlanDetails(List<MonthEngineerImplPlanDetail> monthEngineerImplPlanDetails) {
		this.monthEngineerImplPlanDetails = monthEngineerImplPlanDetails;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}
    
    
}