package com.pcitc.base.engin.construct.constructProcess;

import java.io.Serializable;

import com.pcitc.base.util.SearchInfo;

public class MonthEngineerExplain extends SearchInfo implements Serializable{
	
	private static final long serialVersionUID = 1L;
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_explain.data_id
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    private String dataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_explain.create_user
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_explain.create_date
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_explain.update_user
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_explain.update_date
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_explain.status
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_explain.audit_status
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    private String auditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_explain.company_code
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    private String companyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_explain.project_id
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    private String projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_explain.form_code
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    private String formCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_explain.wbs_name
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    private String wbsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_explain.wbs_code
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    private String wbsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_explain.construct_unit_name
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    private String constructUnitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_explain.construct_unit_code
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    private String constructUnitCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_explain.supervisor_unit_name
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    private String supervisorUnitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_explain.supervisor_unit_code
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    private String supervisorUnitCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_explain.project_department_name
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    private String projectDepartmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_explain.project_department_code
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    private String projectDepartmentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_explain.plan_month
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    private String planMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_explain.edit_month
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    private String editMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_explain.plan_description
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    private String planDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_explain.progress_control_point
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    private String progressControlPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_explain.guarantee_measures
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    private String guaranteeMeasures;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construct_month_engineer_explain.incomplete_content
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    private String incompleteContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_explain.data_id
     *
     * @return the value of construct_month_engineer_explain.data_id
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public String getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_explain.data_id
     *
     * @param dataId the value for construct_month_engineer_explain.data_id
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public void setDataId(String dataId) {
        this.dataId = dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_explain.create_user
     *
     * @return the value of construct_month_engineer_explain.create_user
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_explain.create_user
     *
     * @param createUser the value for construct_month_engineer_explain.create_user
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_explain.create_date
     *
     * @return the value of construct_month_engineer_explain.create_date
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_explain.create_date
     *
     * @param createDate the value for construct_month_engineer_explain.create_date
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_explain.update_user
     *
     * @return the value of construct_month_engineer_explain.update_user
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_explain.update_user
     *
     * @param updateUser the value for construct_month_engineer_explain.update_user
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_explain.update_date
     *
     * @return the value of construct_month_engineer_explain.update_date
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_explain.update_date
     *
     * @param updateDate the value for construct_month_engineer_explain.update_date
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_explain.status
     *
     * @return the value of construct_month_engineer_explain.status
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_explain.status
     *
     * @param status the value for construct_month_engineer_explain.status
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_explain.audit_status
     *
     * @return the value of construct_month_engineer_explain.audit_status
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public String getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_explain.audit_status
     *
     * @param auditStatus the value for construct_month_engineer_explain.audit_status
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public void setAuditStatus(String auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_explain.company_code
     *
     * @return the value of construct_month_engineer_explain.company_code
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_explain.company_code
     *
     * @param companyCode the value for construct_month_engineer_explain.company_code
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_explain.project_id
     *
     * @return the value of construct_month_engineer_explain.project_id
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_explain.project_id
     *
     * @param projectId the value for construct_month_engineer_explain.project_id
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_explain.form_code
     *
     * @return the value of construct_month_engineer_explain.form_code
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public String getFormCode() {
        return formCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_explain.form_code
     *
     * @param formCode the value for construct_month_engineer_explain.form_code
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public void setFormCode(String formCode) {
        this.formCode = formCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_explain.wbs_name
     *
     * @return the value of construct_month_engineer_explain.wbs_name
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public String getWbsName() {
        return wbsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_explain.wbs_name
     *
     * @param wbsName the value for construct_month_engineer_explain.wbs_name
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public void setWbsName(String wbsName) {
        this.wbsName = wbsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_explain.wbs_code
     *
     * @return the value of construct_month_engineer_explain.wbs_code
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public String getWbsCode() {
        return wbsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_explain.wbs_code
     *
     * @param wbsCode the value for construct_month_engineer_explain.wbs_code
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public void setWbsCode(String wbsCode) {
        this.wbsCode = wbsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_explain.construct_unit_name
     *
     * @return the value of construct_month_engineer_explain.construct_unit_name
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public String getConstructUnitName() {
        return constructUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_explain.construct_unit_name
     *
     * @param constructUnitName the value for construct_month_engineer_explain.construct_unit_name
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public void setConstructUnitName(String constructUnitName) {
        this.constructUnitName = constructUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_explain.construct_unit_code
     *
     * @return the value of construct_month_engineer_explain.construct_unit_code
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public String getConstructUnitCode() {
        return constructUnitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_explain.construct_unit_code
     *
     * @param constructUnitCode the value for construct_month_engineer_explain.construct_unit_code
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public void setConstructUnitCode(String constructUnitCode) {
        this.constructUnitCode = constructUnitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_explain.supervisor_unit_name
     *
     * @return the value of construct_month_engineer_explain.supervisor_unit_name
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public String getSupervisorUnitName() {
        return supervisorUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_explain.supervisor_unit_name
     *
     * @param supervisorUnitName the value for construct_month_engineer_explain.supervisor_unit_name
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public void setSupervisorUnitName(String supervisorUnitName) {
        this.supervisorUnitName = supervisorUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_explain.supervisor_unit_code
     *
     * @return the value of construct_month_engineer_explain.supervisor_unit_code
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public String getSupervisorUnitCode() {
        return supervisorUnitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_explain.supervisor_unit_code
     *
     * @param supervisorUnitCode the value for construct_month_engineer_explain.supervisor_unit_code
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public void setSupervisorUnitCode(String supervisorUnitCode) {
        this.supervisorUnitCode = supervisorUnitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_explain.project_department_name
     *
     * @return the value of construct_month_engineer_explain.project_department_name
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public String getProjectDepartmentName() {
        return projectDepartmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_explain.project_department_name
     *
     * @param projectDepartmentName the value for construct_month_engineer_explain.project_department_name
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public void setProjectDepartmentName(String projectDepartmentName) {
        this.projectDepartmentName = projectDepartmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_explain.project_department_code
     *
     * @return the value of construct_month_engineer_explain.project_department_code
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public String getProjectDepartmentCode() {
        return projectDepartmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_explain.project_department_code
     *
     * @param projectDepartmentCode the value for construct_month_engineer_explain.project_department_code
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public void setProjectDepartmentCode(String projectDepartmentCode) {
        this.projectDepartmentCode = projectDepartmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_explain.plan_month
     *
     * @return the value of construct_month_engineer_explain.plan_month
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public String getPlanMonth() {
        return planMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_explain.plan_month
     *
     * @param planMonth the value for construct_month_engineer_explain.plan_month
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public void setPlanMonth(String planMonth) {
        this.planMonth = planMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_explain.edit_month
     *
     * @return the value of construct_month_engineer_explain.edit_month
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public String getEditMonth() {
        return editMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_explain.edit_month
     *
     * @param editMonth the value for construct_month_engineer_explain.edit_month
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public void setEditMonth(String editMonth) {
        this.editMonth = editMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_explain.plan_description
     *
     * @return the value of construct_month_engineer_explain.plan_description
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public String getPlanDescription() {
        return planDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_explain.plan_description
     *
     * @param planDescription the value for construct_month_engineer_explain.plan_description
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public void setPlanDescription(String planDescription) {
        this.planDescription = planDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_explain.progress_control_point
     *
     * @return the value of construct_month_engineer_explain.progress_control_point
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public String getProgressControlPoint() {
        return progressControlPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_explain.progress_control_point
     *
     * @param progressControlPoint the value for construct_month_engineer_explain.progress_control_point
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public void setProgressControlPoint(String progressControlPoint) {
        this.progressControlPoint = progressControlPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_explain.guarantee_measures
     *
     * @return the value of construct_month_engineer_explain.guarantee_measures
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public String getGuaranteeMeasures() {
        return guaranteeMeasures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_explain.guarantee_measures
     *
     * @param guaranteeMeasures the value for construct_month_engineer_explain.guarantee_measures
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public void setGuaranteeMeasures(String guaranteeMeasures) {
        this.guaranteeMeasures = guaranteeMeasures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construct_month_engineer_explain.incomplete_content
     *
     * @return the value of construct_month_engineer_explain.incomplete_content
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public String getIncompleteContent() {
        return incompleteContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construct_month_engineer_explain.incomplete_content
     *
     * @param incompleteContent the value for construct_month_engineer_explain.incomplete_content
     *
     * @mbggenerated Fri Sep 07 17:11:00 CST 2018
     */
    public void setIncompleteContent(String incompleteContent) {
        this.incompleteContent = incompleteContent;
    }
}