package com.pcitc.base.workflow;

public class SysFunctionProdef {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function_prodef.function_prodef_id
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    private String functionProdefId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function_prodef.function_name
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    private String functionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function_prodef.function_id
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    private String functionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function_prodef.prodef_name
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    private String prodefName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function_prodef.prodef_id
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    private String prodefId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function_prodef.project_id
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    private String projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function_prodef.unit_id
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    private String unitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function_prodef.project_name
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function_prodef.unit_name
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    private String unitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function_prodef.status
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function_prodef.create_date
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function_prodef.remarks
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function_prodef.create_person_id
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    private String createPersonId;
    
    
    private String unitValue;
    private String unitShow;
    
    public String getUnitShow() {
		return unitShow;
	}

	public void setUnitShow(String unitShow) {
		this.unitShow = unitShow;
	}

	public String getUnitValue() {
		return unitValue;
	}

	public void setUnitValue(String unitValue) {
		this.unitValue = unitValue;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function_prodef.function_prodef_id
     *
     * @return the value of sys_function_prodef.function_prodef_id
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    public String getFunctionProdefId() {
        return functionProdefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function_prodef.function_prodef_id
     *
     * @param functionProdefId the value for sys_function_prodef.function_prodef_id
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    public void setFunctionProdefId(String functionProdefId) {
        this.functionProdefId = functionProdefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function_prodef.function_name
     *
     * @return the value of sys_function_prodef.function_name
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    public String getFunctionName() {
        return functionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function_prodef.function_name
     *
     * @param functionName the value for sys_function_prodef.function_name
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    public void setFunctionName(String functionName) {
        this.functionName = functionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function_prodef.function_id
     *
     * @return the value of sys_function_prodef.function_id
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    public String getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function_prodef.function_id
     *
     * @param functionId the value for sys_function_prodef.function_id
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    public void setFunctionId(String functionId) {
        this.functionId = functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function_prodef.prodef_name
     *
     * @return the value of sys_function_prodef.prodef_name
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    public String getProdefName() {
        return prodefName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function_prodef.prodef_name
     *
     * @param prodefName the value for sys_function_prodef.prodef_name
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    public void setProdefName(String prodefName) {
        this.prodefName = prodefName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function_prodef.prodef_id
     *
     * @return the value of sys_function_prodef.prodef_id
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    public String getProdefId() {
        return prodefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function_prodef.prodef_id
     *
     * @param prodefId the value for sys_function_prodef.prodef_id
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    public void setProdefId(String prodefId) {
        this.prodefId = prodefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function_prodef.project_id
     *
     * @return the value of sys_function_prodef.project_id
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function_prodef.project_id
     *
     * @param projectId the value for sys_function_prodef.project_id
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function_prodef.unit_id
     *
     * @return the value of sys_function_prodef.unit_id
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    public String getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function_prodef.unit_id
     *
     * @param unitId the value for sys_function_prodef.unit_id
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    public void setUnitId(String unitId) {
        this.unitId = unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function_prodef.project_name
     *
     * @return the value of sys_function_prodef.project_name
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function_prodef.project_name
     *
     * @param projectName the value for sys_function_prodef.project_name
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function_prodef.unit_name
     *
     * @return the value of sys_function_prodef.unit_name
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function_prodef.unit_name
     *
     * @param unitName the value for sys_function_prodef.unit_name
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function_prodef.status
     *
     * @return the value of sys_function_prodef.status
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function_prodef.status
     *
     * @param status the value for sys_function_prodef.status
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function_prodef.create_date
     *
     * @return the value of sys_function_prodef.create_date
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function_prodef.create_date
     *
     * @param createDate the value for sys_function_prodef.create_date
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function_prodef.remarks
     *
     * @return the value of sys_function_prodef.remarks
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function_prodef.remarks
     *
     * @param remarks the value for sys_function_prodef.remarks
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function_prodef.create_person_id
     *
     * @return the value of sys_function_prodef.create_person_id
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    public String getCreatePersonId() {
        return createPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function_prodef.create_person_id
     *
     * @param createPersonId the value for sys_function_prodef.create_person_id
     *
     * @mbggenerated Mon Jun 11 19:05:31 CST 2018
     */
    public void setCreatePersonId(String createPersonId) {
        this.createPersonId = createPersonId;
    }
}